### ISSUE TITLE
Change admin default role to not be "readonly"

### ISSUE THREAD

**Issue by elfisher** [opendistro-for-elasticsearch/security#10]
We should change the admin [default config](https://github.com/opendistro-for-elasticsearch/security/blob/55a7ee1327abbd98245a71c01457cd7adc550888/securityconfig/internal_users.yml#L6) to not be read only. This will enable users to change it in Kibana. Currently users need to update the yml before launching the cluster.

**Comment by aetter** [comment]
Hi @elfisher, I think the appeal of marking the `admin` user read-only is that you need SSH access to the cluster to modify the account and explicitly can't do it using the REST API/Kibana. Is the convenience here a worthwhile tradeoff for the drop in out-of-the-box security?

**Comment by elfisher** [comment]
@aetter That's a fair point. I think the challenge is with the docker it's not clear how to overwrite these settings. If we more clearly document that process we should be good.

@shivdoshi or @hardik-k-shah do either of you have any thoughts on this? I'm leaning with what @aetter is thinking here.

**Comment by hardik-k-shah** [comment]
Yes, I am agree with @aetter for this and prefer documenting this instead tradeoff. And we should also mention about another readonly user kibanaserver. 

As mentioned by @aetter, user must have SSH access to change this admin or other readonly user password.  As this is demo configuration, we have kept those password simple. Ideally, user should setup strong password for all these readonly users and we should document how to do it for both docker and RPM distribution. (@aetter has already documented for RPM here: https://github.com/opendistro/for-elasticsearch-docs/issues/5)

Additionally, if user wants to setup more admin user, they can create more users with admin role with their custom password through Kibana UI.

**Comment by elfisher** [comment]
@hardik-k-shah makes sense. @aetter are you thinking of documenting overwriting the whole default internal_users.yml file via mounting from a file on local disk?

**Comment by aetter** [comment]
@elfisher, yeah, that's what I was thinking. I figure any time you have to get Bash access to the container and issue commands, it's a failure on our part, so I'd like to handle the admin configuration via overrides/Docker Compose. Then you can use Kibana to set up all the other users.

I have what appears to be a working test setup, but I need to do additional testing and verify with others that the steps I took to get things working were sane.

**Comment by aetter** [comment]
Closing this out now that this is documented.
