### ISSUE TITLE
no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]

### ISSUE THREAD

**Issue by r00t9** [opendistro-for-elasticsearch/security#100]
I tried to run this command but i get the error

`curl -XPUT 'localhost:9200/_settings' -H 'Content-Type: application/json' -u admin --insecure -d '{
    "index" : {
        "number_of_replicas" : 0
    }
}'`

Error: 

>  {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]"},"status":403}%                                                                                                                        

i have on the config file:
opendistro_security.ssl.http.enabled: false
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

Any ideas ? :)

**Comment by chuanzgh** [comment]
You're probably hitting .opendistro_security which requires admin certificate to write to (yeah, just admin user alone doesn't cut it). You can try to attach the admin cert along with your curl request https://github.com/opendistro-for-elasticsearch/security/issues/107#issuecomment-519775491

**Comment by debjanibnrj** [comment]
Thanks for the answer @chuanzgh. @r00t9 you will have to use the admin cert and key to make changes to the .opendistro_security index.

`curl -XPUT 'localhost:9200/.opendistro_security/_settings' -H 'Content-Type: application/json'  --cert chain.pem --key kirk.key.pem  --insecure -d '{ "index" : { "number_of_replicas" : 0 } }'`
