### ISSUE TITLE
[Feature Request] Will the password complexity check mechanism be added in the future?

### ISSUE THREAD

**Issue by EasonJiang24** [opendistro-for-elasticsearch/security#1007]
Our products use the user name and password authentication mechanism. Will the password complexity check mechanism be added in the future?

**Comment by hardik-k-shah** [comment]
Feature to configure password strength rules for internal user is available. It can be configured through below settings in elasticsearch.yml 
 
Password validation rules can be configured through regex. With below regex example, user must need password with 8 characters length and must include minimum one upercase, one kower case, one digit, and one special character. Also you can customize error message in case if user missed following suggested password strength. 

```
 oendistro_security.restapi.password_validation_regex: '(?=.*[A-Z])(?=.*[^a-zA-Z\d])(?=.*[0-9])(?=.*[a-z]).{8,}'
 opendistro_security.restapi.password_validation_error_message: "Password must be minimum 8 characters long and must contain minimum one uppercase letter, one lowercase letter, one digit, and one special character."
```

**Comment by hardik-k-shah** [comment]
Please re-open the issue if you still have further questions.
