### ISSUE TITLE
[Question] Permissions for Delete _all

### ISSUE THREAD

**Issue by shyim** [opendistro-for-elasticsearch/security#1011]
When I try to delete all indices using `DELETE /_all` I get always a Security Error. I have seen also some Issues here, that I need more permissions. But the Role that my user `admin` is attached to `all-access`. It has a wildcard on all sections. 
Did I miss something? 

![grafik](https://user-images.githubusercontent.com/6224096/106933200-f14a8180-6718-11eb-8702-8fba32752126.png)

**Comment by hardik-k-shah** [comment]
Can you provide exception? 
Most likely it is due to .opendistro_security index.  You may need to exclude this index while deleting. 


You can try deleting all indices using 

`curl -X DELETE -i 'http://{server}:{port}/*,-.opendistro_security'`

**Comment by shyim** [comment]
Thanks works for me :)
