### ISSUE TITLE
Issue with document-level security expression and date range

### ISSUE THREAD

**Issue by mattvl** [opendistro-for-elasticsearch/security#1038]
I am having an issue while trying to set a document-level security expression in my opendistro-for-elasticsearch instance. This is the expression I'm trying to apply:

```
{
  "bool": {
    "must": [
      {
        "terms": {
          "name": [
            "John"
          ]
        }
      },
      {
        "range": {
          "birthdate": {
            "gte": "now-30y"
          }
        }
      }
    ]
  }
}
```
I am getting the following error message when I try to search the index with a user linked to the Role:

> Request failed to execute. Call: Status code 400 from: POST /users/_search?typed_keys=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: parse_exception Reason: "could not read the current timestamp" CausedBy: "Type: illegal_argument_exception Reason: "'now' is not allowed in DLS queries"""

In the elasticsearch forum, I was pointed to [these limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-limitations.html#field-document-limitations), but I'm not sure if opendistro uses xpack under the hood or if it implements the security roles in a different way.

Do you have any idea on how to create a document-level security role with a relative date to now?

Thanks.[](url)

**Comment by mattvl** [comment]
Playing around with the repository I found out that the "culprit" is this line:

https://github.com/opendistro-for-elasticsearch/security/blob/68e7e08e2f4306f974c2c0b17c8e50fa5a67c4d4/src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityFlsDlsIndexSearcherWrapper.java#L65

and the configuration value that it tries to get. If I add that config value to `elasticsearch.yml` and set it to `true`, everything works fine and the document-level security expression is applied correctly.

Now I'm wondering: probably there's a reason why that line is there, does anybody know?

Thanks.

**Comment by vrozov** [comment]
It is a security risk, as `now` is not fixed, so admin needs to accept that DLS definition depends on the time query is executed.
