### ISSUE TITLE
opendistro_security.audit.config.disabled_rest_categories property does not work

### ISSUE THREAD

**Issue by dert1714** [opendistro-for-elasticsearch/security#1039]
Hi,
I try to see "AUTHENTICATED" events in audit logs which are disabled by default. For this purpose I override 
`opendistro_security.audit.config.disabled_rest_categories: NONE`
property. My full elasticsearch.yaml config is
```
opendistro_security.ssl.transport.pemcert_filepath: elk-transport-crt.pem
opendistro_security.ssl.transport.pemkey_filepath: elk-transport-key.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: elk-transport-root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: false
opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true
opendistro_security.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test,C=DE
opendistro_security.audit.type: log4j
opendistro_security.audit.config.log4j.logger_name: console
opendistro_security.audit.config.disabled_rest_categories: NONE
opendistro_security.audit.ignore_users: NONE
opendistro_security.audit.ignore_requests: NONE
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
opendistro_security.system_indices.enabled: true
opendistro_security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-
detection-state", ".opendistro-reports-*", ".opendistro-notifications-*"]
cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 3
```
Expected result: success authentication is logged
Actual result: there are no audit logs for authenticated events.

Please help me to fix the issue.
thanks

Best Regards,
Valerii

**Comment by vrozov** [comment]
Please check documentation on how to enable and manage audit logging. Using `elasticsearch.yml` to enable audit logging is deprecated.

**Comment by dert1714** [comment]
@vrozov thank you for your answer! Could you provide relevant link on the documentation because [this one](https://opendistro.github.io/for-elasticsearch-docs/docs/security/audit-logs/) contains mentioned approach - add `opendistro_security.audit.config.disabled_rest_categories` property directly to the `elasticsearch.yml` file. But in elasticsearch logs I can see that this property is deprecated. `Depricated` is not `should not work`. 
Thank you in advance!
