### ISSUE TITLE
delayed response over https

### ISSUE THREAD

**Issue by Balaji8051** [opendistro-for-elasticsearch/security#1060]
I have a single node setup of elasticsearch, where I have a dozen of indices created with each of overall size not exceeding an MB. The elasticsearch query responds superfast over HTTP, whereas causes significant delay (say 8s) over HTTPS. I'm pretty sure that I don't have to add nodes to my cluster for this issue. I have also tried disabling audit logs thinking that was a factor, but didn't help.

Any suggestion or help on this matter will be highly appreciated!

Thanks in advance.

**Comment by JJCella** [comment]
I have just updated to 1.13 (single node, small indices) and i am also experiencing huge delays on every request, kibana is now unusable
Tried without https but nothing changed, so not sure if its related to your problem.
I think someone talked about disabling http2 ? maybe its worth the try

**Comment by Balaji8051** [comment]
> I have just updated to 1.13 (single node, small indices) and i am also experiencing huge delays on every request, kibana is now unusable
> Tried without https but nothing changed, so not sure if its related to your problem.
> I think someone talked about disabling http2 ? maybe its worth the try

can you tell me how to disable http2? as far as i checked, i didn't see anything about turning http2 off in the documentation.

**Comment by JJCella** [comment]
I thought maybe you were using a reverse proxy in front of your elasticsearch nodes that have http2 enabled.

I am using ldap for user auth and using a local user (ldap bypass) fix delays.  #1061 solves my issue.
Are you testing http vs http2 in the same conditions ? (same user / authc / authz ?)

**Comment by Balaji8051** [comment]
I don't have any reverse proxy enabled. I use http and https, no http2. And I'm using the default internal user. Earlier, I had mentioned it was taking 8s, it's due to series of queries. I just analysed found that a query over HTTP takes about 15ms and the same query over HTTPS takes about a second(990 ms). I wonder if handshake could consistently cause delay of about a second(975ms) for every request!

**Comment by mxmorin** [comment]
Maybe #1062
See also : https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/664#issuecomment-790001149

**Comment by bbarani** [comment]
@Balaji8051 can you try 1.13.1 version and let us know if you are still facing this issue?

**Comment by Balaji8051** [comment]
@bbarani I see the performance is significantly improved! Thanks for the fix!
