### ISSUE TITLE
Severe performance penalty on 1.13.0.0

### ISSUE THREAD

**Issue by trexx** [opendistro-for-elasticsearch/security#1062]
I have a ELK cluster which on 7.10.0 / 1.12.0.0, and during an average day was able to process around 15,000 - 20,000 requests per second from logstash.
Upon upgrading to 7.10.2 / 1.13.0.0, this plummets to 3,000 per second.

Disabling the security plugin via "opendistro_security.disabled: true" in elasticsearch.yml and going over HTTP, the cluster returns to the speeds above.
Additionally when upgrading, I noticed an increase in CPU utilisation across all nodes in the cluster by 15-20% when sitting idle (20 events a second).

**Comment by trexx** [comment]
Just noticed this: https://github.com/opendistro-for-elasticsearch/security/pull/1061

**Comment by sujithvm** [comment]
Fixed with #1061 Please watch out for upcoming release

**Comment by mxmorin** [comment]
Can we have a fix quickly because our production env is very instable and we loose a lot of requests ?
Thanks in advance

**Comment by trexx** [comment]
As of writing the 1.13.1.0-rc2 tag contains some essential fixes.
Its very easy to build the plugin from the source by following instructions in the repos readme.
