### ISSUE TITLE
Error - Tenant indices migration failed

### ISSUE THREAD

**Issue by aradhell** [opendistro-for-elasticsearch/security#11]
Hello,

 I am having Kibana status - yellow and "plugin:opendistro_security@6.5.4 | Tenant indices migration failed"

while trying to browse :5601,

and I don't know if it is relevant but also seeing this log, any idea? Thanks!

**Comment by aradhell** [comment]
`opendistro_security.multitenancy.enabled: false`

solved my problem.

https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/2

**Comment by hardik-k-shah** [comment]
Fix for "tenant migration failure" has been merged through [this PR](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/2). We are working on release process and will be releasing it soon.
