### ISSUE TITLE
SAML w/ Azure Federation Metadata Error

### ISSUE THREAD

**Issue by bsanderrmg** [opendistro-for-elasticsearch/security#115]
When I try to set up SAML with our Azure AD, I'm getting an error with the Base64Utility.decode() function. My best guess is that the function is not able to parse the certificate from the XML, but it's just a guess. I've tried using the `idp.pemcert_content` option as well, but I don't think that's what it's for.  I'll post a link to an Azure Federation Metadata XML sample, which has the same format as our Azure application.

XML sample:
https://login.microsoftonline.com/common/FederationMetadata/2007-06/FederationMetadata.xml

Error:

>  Error creating HTTPSamlAuthenticator: java.lang.SecurityException: org.apache.cxf.common.util.Base64Exception: Runtime exception in Base64Utility.decode() during output. SAML authentication will not work

Let me know if you need more details.

**Comment by dinusX** [comment]
Hi @bsanderrmg ,

When do you get this exception ? while accessing Kibana page for the first time or after logging-in on AD login page ?

This exception might be happening as part of processing SAML requests, which is also an XML content that is sent in the HTTP request.
There are several browser extensions that you can use to view the SAML request and see if something is missing there.

Do you have also any stack-trace for this exception ?

**Comment by menjaben** [comment]
Hey @dinusX ,

Thanks for getting back to me. It's been a while since I submitted this issue but I've since been able to get this to work. This was likely a YAML formatting issue on my part, don't believe there is any current issue with the SAML function itself. Sorry I don't have more info.

I believe this issue can be closed.
