### ISSUE TITLE
/usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh is not executable

### ISSUE THREAD

**Issue by opoplawski** [opendistro-for-elasticsearch/security#121]
I have no idea where this is configured, but /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh is not marked as executable in opendistro-security-1.1.0.0-0.noarch.rpm

**Comment by aetter** [comment]
Hi @opoplawski, can you try running `chmod +x /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh`? Thanks a bunch.

**Comment by opoplawski** [comment]
Well, yeah, I can obviously fix it after the fact, and it works fine then.  But it should be shipped as executable.

**Comment by aetter** [comment]
Agreed, just wanted to make sure you weren't blocked. 👍

**Comment by vrozov** [comment]
Fixed by https://github.com/opendistro-for-elasticsearch/security/pull/472
