### ISSUE TITLE
SAML documentation issue and startup debugging

### ISSUE THREAD

**Issue by sathomps** [opendistro-for-elasticsearch/security#144]
The configuration specified [here](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/saml/) specifies the following.

```
saml_auth_domain:
    enabled: true
```

When adding this, the ES cluster fails to start up - no errors or warnings as to why in the logs.  Accessing cluster health returns `Open Distro Security not initialized`

When using the configuration specified [here](https://aws.amazon.com/blogs/opensource/open-distro-for-elasticsearch-single-sign-on-saml-adfs/), cluster starts up and SAML works.

```
saml_auth_domain:
    http_enabled: true
    transport_enabled: false
```

**Comment by alolita** [comment]
Hi @sathomps thanks for your patience. Folks working on this code base will take a look and respond.

**Comment by aetter** [comment]
Thanks @sathomps, I've updated the samples in the docs. https://github.com/opendistro/for-elasticsearch-docs/commit/1bc967b627c6bc60680fadeeab3eecb02d7e3215
