### ISSUE TITLE
LDAPS connections not closing

### ISSUE THREAD

**Issue by gplechuck** [opendistro-for-elasticsearch/security#159]
Hi guys ,

Have configured LDAP authc and authz to query an LDAPS server and noticed that connections to the LDAPS server are not closing. Every subsequent LDAP auth query adds 2 new connections that stay open until forcibly terminated.

Not seeing the same issue on queries against the same LDAP server from an Elasticsearch cluster with the X-Pack LDAP implementation. LDAP queries are serviced and the connection is closed in a timely manner.

Have compared a traffic capture from both implementations to see if there is a difference, see attached (ldap-opendistro.png, ldap-xpack.png) .  

In both examples , 10.0.42.5 is the client and 10.0.42.6 is the LDAP server. 

![ldaps-opendistro](https://user-images.githubusercontent.com/19838621/67476192-6d69a480-f64f-11e9-958a-da6549bbd1c7.png)

![ldaps-xpack](https://user-images.githubusercontent.com/19838621/67476207-76f30c80-f64f-11e9-927c-c86faddae298.png)

Have noticed that in the case of the connections that do not close, the client never ACKS the servers FIN/ACK when the connection is closing. I'm wondering if this is responsible for the open connections. 

What do you think about this, is this a known issue? 

Package and OS details : 

Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

elasticsearch-oss               7.2.0
opendistro-alerting             1.2.0.0-1
opendistro-job-scheduler        1.2.0.0-1
opendistro-performance-analyzer 1.2.0.0-1
opendistro-security             1.2.0.0-0
opendistro-sql                  1.2.0.0-1
opendistroforelasticsearch      1.2.0-1

LDAP Server - OpenLDAP
slapd                               2.4.40+dfsg-1+deb8u3

Cheers

**Comment by Jakob3xD** [comment]
I can confirm that I experience the same issue.

**Comment by manavkapoor** [comment]
Experiencing the same issue. @gplechuck @Jakob3xD question for you guys: how fast does LDAP work for you? We are seeing LDAP queries take 10-15 seconds and have ensured our queries run adequately using `ldapsearch`

Would really appreciate help on the issue @opendistrocommunity

**Comment by hardik-k-shah** [comment]
We have added fixed some of the leaked LDAP connection issues through this PR: https://github.com/opendistro-for-elasticsearch/security-advanced-modules/pull/57  

This might solve a problem.

**Comment by avanand-git** [comment]
We are also seeing this leak in ES 6.7.2, any plans on back porting this fix?

**Comment by gplechuck** [comment]
Thanks @hardik-k-shah 

Installed Elasticsearch 7.3.2 and built the security plugin v 1.3.0 and can confirm that the issue appears to be resolved.

Would you know when the official release of 1.3.0 is scheduled for?
