### ISSUE TITLE
openid redirect logout error

### ISSUE THREAD

**Issue by gpicavet** [opendistro-for-elasticsearch/security#160]
Using Keycloak as an Identity Provider

When logging out from kibana, keycloak is reporting a 400 error with this request :

https://HOST/auth/realms/REALM/protocol/openid-connect/logout?post_logout_redirect_uri=https://HOST/opendistro/app/kibana&id_token_hint=xxxxx

Kibana session is still valid

It seems that the default post_logout_redirect_uri is invalid, is there a way to configure it, like the xpack openid ? (https://www.elastic.co/guide/en/elasticsearch/reference/master/oidc-guide-authentication.html)

**Comment by artb1sh** [comment]
Give u config config.yml and kibana.yml

**Comment by artb1sh** [comment]
@gpicavet

**Comment by gpicavet** [comment]
`# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "dev-factory-elastic-01.open.naval-group.com"

path.data: /data/kibana

# Specifies locale to be used for all localizable strings, dates and number formats.
i18n.locale: "fr"
# pour appeler les API kibana
csp.strict: true

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
server.basePath: /opendistro
server.rewriteBasePath: true
#server.ssl.enabled: true
#server.ssl.certificate: /etc/kibana/node.pem
#server.ssl.key: /etc/kibana/node-key.pem

elasticsearch.hosts: https://dev-factory-elastic-01.open.naval-group.com:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

opendistro_security.auth.type: "openid"
opendistro_security.openid.connect_url: "https://developers.naval-group.com/auth/realms/factory/.well-known/openid-configuration"
opendistro_security.openid.client_id: "opendistro"
opendistro_security.openid.client_secret: "7e74b280-6292-47e5-89a2-13684bf3802a"
opendistro_security.openid.base_redirect_url: "https://developers.naval-group.com"`

**Comment by gpicavet** [comment]
Hello

i should specify that kibana is behind a reverse proxy with a base path "/opendistro"

here is the kibana.yml :

server.port: 5601
server.host: "dev-factory-elastic-01.xxx.com"

path.data: /data/kibana

i18n.locale: "fr"
csp.strict: true

server.basePath: /opendistro
server.rewriteBasePath: true

elasticsearch.hosts: https://dev-factory-elastic-01.xxx.com:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

opendistro_security.auth.type: "openid"
opendistro_security.openid.connect_url: "https://developers.xxx.com/auth/realms/factory/.well-known/openid-configuration"
opendistro_security.openid.client_id: "opendistro"
opendistro_security.openid.client_secret: "xxxxxxxxxxx"
opendistro_security.openid.base_redirect_url: "https://developers.xxx.com"

the config.yml :
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: true
          config:
            openid_connect_url: https://developers.xxx.com/auth/realms/factory/.well-known/openid-configuration
            subject_key: email
            roles_key: roles
        authentication_backend:
          type: noop

**Comment by gpicavet** [comment]
It seems not a bug of Kibana
I think the redirect_uri in client's configuration of keycloak was too specific : It works when using "https://developers.xxx.com/opendistro/*"
