### ISSUE TITLE
User Password Reset Error 

### ISSUE THREAD

**Issue by rkredux** [opendistro-for-elasticsearch/security#162]
Opendistro Version 1.2.0

When a user tries to reset the password from Kibana UI Developer console we get an incorrect error handler 

```
{
  "error": "no handler found for uri [/_security/user/username/_password?pretty] and method [POST]"
}
```

Our POST is 

```
POST _security/user/username/_password 
{
"password": "newpasswordtoupdate"
}
```

Which is what is recommended in the Elasticsearch documentation 

https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-change-password.html

Does Opendistro have a different URI path for password reset feature for users with API access?

**Comment by sujithvm** [comment]
@rkredux Please use the API documented here for account password change: https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#change-password
