### ISSUE TITLE
Kibana enable to login with wrong credentials

### ISSUE THREAD

**Issue by cde0** [opendistro-for-elasticsearch/security#163]
I Upgrade from 7.1.0 to 7.2.1 and i can login with wrong credentials, also correct and wrong credentials is the same permission. I tried with ldap and local credentials same behaviour.

Elasticsearch is authenticate correct.

When i run this on elastic
:9200/_opendistro/_security/kibanainfo it return the correct info from ldap.

Linux: Ubuntu 18.04.2 LTS
Elastic version:
elasticsearch-oss 7.2.1
opendistro-security 1.2.1.0-0
opendistroforelasticsearch 1.2.1-1

kibana.yml:

```
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opendistro_security.allow_client_certificates: true
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
opendistro_security.multitenancy.enable_filter: true
```

**Comment by dinusX** [comment]
Hi, 

were you able to fix the issue ?

If not, could you share more details about your configuration:
- Do you use basic auth (internal database) ?
- when you say wrong and correct credentials, are those for different users ? What do you mean by wrong credentials ?

**Comment by vrozov** [comment]
Please re-open if this is still an issue and provide requested info
