### ISSUE TITLE
authentication_backend setting question.

### ISSUE THREAD

**Issue by avanand-git** [opendistro-for-elasticsearch/security#169]
Is the authentication_backend, type: intern or type:internal?

        authentication_backend:
          type: intern

Documentation says internal, but all examples show "intern"

https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml

**Comment by hardik-k-shah** [comment]
It is type: intern

**Comment by avanand-git** [comment]
![image](https://user-images.githubusercontent.com/58018202/69394958-5770f300-0c92-11ea-965d-dd575d01d225.png)

This confused me...
# Authc
#   internal
#   noop
#   ldap

**Comment by hardik-k-shah** [comment]
Let us know if you need further help understanding this. Or point us to documentation link which we can improve further. 
Please feel free to reopen this issue if you need further help.
