### ISSUE TITLE
Unable to update indices settings

### ISSUE THREAD

**Issue by orest-gulman** [opendistro-for-elasticsearch/security#170]
Unable to update indices settings when trying to update all indices:
![image](https://user-images.githubusercontent.com/10500949/69337336-495aac80-0c69-11ea-81fd-68b39467f0cb.png)
https://www.elastic.co/guide/en/elasticsearch/reference/7.2/indices-update-settings.html#indices-update-settings

**Comment by chuanzgh** [comment]
You can refer to this for updating .opendistro_security
https://github.com/opendistro-for-elasticsearch/security/issues/107#issuecomment-519775491

**Comment by palashhedau** [comment]
This can be achieved by admin certificate with security enabled

curl -k --cert key.pem --key kirk.key.pem -X PUT -H "Content-Type: application/json" -d '{"index.blocks.read_only_allow_delete": null }' https://localhost:9200/.opendistro_security/_settings

I am closing this ticket, please feel free to open in case of any more doubts.
