### ISSUE TITLE
Suggestion: Cert rollover without restart

### ISSUE THREAD

**Issue by gna582** [opendistro-for-elasticsearch/security#172]
Dear developers,

I would like to suggest a feature that not even x-pack has:
Cert rollover without restart

Certificates expire after a few months and thus need to be replaced beforehand.
The current workflow is replacing the certificate file and restarting the ES service.

It would be great if it periodically checked the hash of the certificate file and reload its content if it changed. If that doesn't work it would be great to have some sort of "reload" that doesn't restart the whole process.

It would greatly improve the workflow using automated CA's like letsencrypt or companyinternal CA's that have the same workflow.

The same should obviously be true for the kibana plugin.

Thank you for listening!

**Comment by gna582** [comment]
I have to correct myself.
X-Pack does in fact already implement this:
https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html#tls-transport
Sorry for spreading misinformation.

**Comment by debjanibnrj** [comment]
Hi @gna582,

Thanks for your interest in improving our community. This feature is available in the latest versions of ODFE security for version 0.9 onwards.

For more details you can refer to - https://github.com/opendistro-for-elasticsearch/security/pull/238
