### ISSUE TITLE
Unable to unlock read only indexes

### ISSUE THREAD

**Issue by mmiller1** [opendistro-for-elasticsearch/security#177]
My cluster hit the disk threshold limits which caused all indexes to go read-only. Currently when I try to unlock the indexes (as the admin user) I get an access denied error, which seems to stem from the audit log index also being read only. I'm fairly certain that the cluster is hosed in this state as I cannot unmark the index "security-auditlog-2019.12.06" as read only.
```
[root@elasticsearch-master-0 config]# curl -k --cert admin-crt.pem --key admin-key.pem -X PUT -H "Content-Type: application/json" -d '{"index.blocks.read_only_allow_delete": null }' https://localhost:9200/security-auditlog-2019.12.06/_settings
Unauthorized
```
```
elasticsearch-master-0 elasticsearch [2019-12-06T17:10:39,366][ERROR][c.a.o.s.a.s.InternalESSink] [elasticsearch-master-0] Unable to index audit log {"audit_cluster_name":"elasticsearch","audit_rest_request_params":{"index":"security-auditlog-2019.12.06"},"audit_node_name":"elasticsearch-master-0","audit_category":"FAILED_LOGIN","audit_request_origin":"REST","audit_request_body":"{\"index.blocks.read_only_allow_delete\": null }","audit_node_id":"4FkOLFbgR-aYRNwYYsBtQw","audit_request_layer":"REST","audit_rest_request_path":"/security-auditlog-2019.12.06/_settings","@timestamp":"2019-12-06T17:10:39.362+00:00","audit_request_effective_user_is_admin":false,"audit_format_version":4,"audit_request_remote_address":"127.0.0.1","audit_node_host_address":"10.244.97.48","audit_rest_request_headers":{"Accept":["*/*"],"User-Agent":["curl/7.29.0"],"Host":["localhost:9200"],"Content-Length":["46"],"Content-Type":["application/json"]},"audit_request_effective_user":"<NONE>","audit_node_host_name":"10.244.97.48"} due to ClusterBlockException[index [security-auditlog-2019.12.06] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
elasticsearch-master-0 elasticsearch org.elasticsearch.cluster.block.ClusterBlockException: index [security-auditlog-2019.12.06] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];
```

Is there a way to temporarily disable the security plugin so I can unlock the indexes and then re-enable it? Also, as an enhancement, would it be a good idea to default creation of these indexes with the read only locking disabled?

**Comment by mmiller1** [comment]
So I managed to get the cluster back to a green state, the process for me was to disable the security in elasticsearch.yml as mentioned here: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/disable/
restart all nodes in the cluster then unlock the indexes 
```
curl -X PUT -H "Content-Type: application/json" -d '{"index.blocks.read_only_allow_delete": null }' http://localhost:9200/_all/_settings
```
then re-enable the security plugin and restart all nodes again. 

I can only imagine this would be a fairly common issue when running clusters with limited disk capacity, and the resolution (at least for me, and maybe not the most efficient) requires a total cluster outage. Am I missing something that resulted in this state?

**Comment by m4rkw** [comment]
Hi @mmiller1 we ran into this problem yesterday and were able to resolve it without restarting the cluster. I think you need to authenticate curl using the admin certificate and key rather than static credentials. If you were using static credentials that's probably why it didn't work.

**Comment by rlk5546** [comment]
I ran into the same issue a couple months ago.  Since this operates on the .opendistro_security index, you must use the admin certs or disable security to execute successfully.

```
curl -k --cert /path/to/admincert.pem --key /path/to/adminkey.key -XPUT "https://localhost:9200/.opendistro_security/_settings" -H "Content-Type: application/json" -d '{"index.blocks.read_only_allow_delete": null }'
```

rlk

**Comment by palashhedau** [comment]
Hope the above solution by @rlk5546 clarifies the solution for the issue.

I am closing the ticket, please feel free to open otherwise.
