### ISSUE TITLE
Poor documentation for client authentication using certificates.

### ISSUE THREAD

**Issue by tconnard** [opendistro-for-elasticsearch/security#188]
At the moment the documentation does not explain how to authenticate a user using a client certificate.

**Comment by alolita** [comment]
Hi @tconnard - can you please either raise a PR contributing any documentation you may have from steps you've used for authentication with certificates or open an issue on https://github.com/opendistro/for-elasticsearch-docs for this documentation to be added.

**Comment by aetter** [comment]
Closing out in favor of https://github.com/opendistro/for-elasticsearch-docs/issues/254
