### ISSUE TITLE
Skip basic auth for the networks in a list

### ISSUE THREAD

**Issue by frutik** [opendistro-for-elasticsearch/security#19]
Hi.

I am trying to setup opendistro in google cloud behind a GCP load balancer.  Is there any way to disable basic auth for the list of networks, to allow healthchecker connect to the host and get status 200?

**Comment by pondohva** [comment]
I have the same issue, but with openID. Health checks fail when status code != 200.

**Comment by pondohva** [comment]
@frutik I've found there is endpoint (/api/status) to get status without auth: 
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/05ea4ee44901371ab53856dac4df1b5b7097e61e/lib/auth/types/AuthType.js#L165

and config for this: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/05ea4ee44901371ab53856dac4df1b5b7097e61e/lib/auth/types/AuthType.js#L48

**Comment by frutik** [comment]
I am going to play with anonymous_auth_enabled: true

**Comment by frutik** [comment]
For some reason, anonymous_auth_enabled: true doesn't work for me. 

Found this endpoint. 
```
curl "localhost:9600/_opendistro/_performanceanalyzer/metrics?metrics=Latency&agg=max" -i
HTTP/1.1 200 OK
Date: Wed, 03 Apr 2019 19:59:47 GMT
Content-type: application/json
Content-length: 98
```

Receiving HTTP 200 OK from this endpoint does not necessarily mean that elasticsearch on 9200 is OK too, but this is better then nothing

**Comment by pondohva** [comment]
@frutik try localhost:9200/api/status

**Comment by hardik-k-shah** [comment]
Hi @frutik and @pondohva ,

You can use health API `https://localhost:9200/_opendistro/_security/health` for your use-case. This health API doesn't require credential and developed specially for health-check operations from loadbalancer.     

```
curl -k https://localhost:9200/_opendistro/_security/health --verbos 
* About to connect() to localhost port 9200 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=node-0.example.com,OU=node,O=node,L=test,DC=de
* 	start date: Apr 22 03:43:47 2018 GMT
* 	expire date: Apr 19 03:43:47 2028 GMT
* 	common name: node-0.example.com
* 	issuer: CN=Example Com Inc. Root CA,OU=Example Com Inc. Root CA,O=Example Com Inc.,DC=example,DC=com
> GET /_opendistro/_security/health HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9200
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 46
< 
* Connection #0 to host localhost left intact
{"message":null,"mode":"strict","status":"UP"}

```

**Comment by ssgao** [comment]
@hardik-k-shah would be great to include this one in the doc https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

**Comment by hardik-k-shah** [comment]
Sure. We will add it into our docs. Thanks!
