### ISSUE TITLE
elasticsearch7.4.0 NoClassDefFoundError: org/elasticsearch/action/StreamableResponseActionType

### ISSUE THREAD

**Issue by ouyangchucai** [opendistro-for-elasticsearch/security#199]
use the elasticsearch 7.4.0 as server and install the opendistro_security-1.3.0.0 plugin, it will throw exception when startup

"stacktrace": ["java.lang.NoClassDefFoundError: org/elasticsearch/action/StreamableResponseActionType"

**Comment by sujithvm** [comment]
opendistro_security-1.3.0.0 is not compatible with Elasticseach 7.4.x . Please use opendistro_security-1.4.0.0 and have a look at the compatibility matrix here https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#plugin-compatibility
