### ISSUE TITLE
Support for Elasticsearch 7.5 or 7.6

### ISSUE THREAD

**Issue by Ricaz** [opendistro-for-elasticsearch/security#241]
Hi! Sorry, I know you must be getting these a lot, but is there anywhere (except watching Git commits) to track progress, or to see a road map?

I'm considering whether to attempt a downgrade from ES 7.5.0 to 7.4.2 or just wait it out. I only need the security plugin, and I don't see any changes in the ES change log, so maybe it will be released soon-ish? Just want to know if I can expect to wait weeks or months.

Thanks!

Edit: I see #220 is merged and #232 is awaiting approval, so maybe this is pretty close? :)

**Comment by sujithvm** [comment]
ES 7.5.2  is currently supported in version opendistro_security-1.5.0.1
