### ISSUE TITLE
Audit Logging for new hot reload feature

### ISSUE THREAD

**Issue by debjanibnrj** [opendistro-for-elasticsearch/security#255]
Based on https://github.com/opendistro-for-elasticsearch/security/pull/238#discussion_r385935539 audit logging needs to be added to hot reload api to note updates have been made to ssl certificates issued on the node.

**Comment by sujithvm** [comment]
Audit logging should log events "AUTHENTICATED", "GRANTED_PRIVILEGES" for any of these API requests. Please reopen if thats not the case.
