### ISSUE TITLE
Missing instructions on how-to build zip plugin

### ISSUE THREAD

**Issue by arthmoeros** [opendistro-for-elasticsearch/security#26]
Since the issue in #7 hasn't been resolved, I tried to build the plugin myself from source, but there are no instructions on how to build the ES plugin zip file, running `mvn install` just compiles the jar file.

**Comment by hardik-k-shah** [comment]
run `mvn clean install` for all packages in following order. This will build jars and store in into local .m2 directory for further use. 
1) security-parent 
2) security-ssl
3) security
4) security-advanced-modules 

After above steps run `mvn package -Padvanced` for security repo to build final artifacts in zip format. Final zip artifacts will be available in target/releases/ directory.
