### ISSUE TITLE
list roles which got via ldap

### ISSUE THREAD

**Issue by diamondized** [opendistro-for-elasticsearch/security#298]
I configured LDAP as a backend for authentication / authorization using `securityconfig/config.yml`.
However, it seems that roles registered in LDAP are not displayed in the `Kibana/Security/Roles` menu.
Are the roles listed in the kibana WebUI only `roles.yaml`, or registered via REST API?

Also, Is it possible to get `rolemapping` via LDAP?

**Comment by palashhedau** [comment]
Hi @diamondized, 
Apologies for the late reply.

Below are my answers

However, it seems that roles registered in LDAP are not displayed in the Kibana/Security/Roles menu. `The roles won't be displayed automatically when ldap is used. They have to be mapped with some backend role. Opendistro security uses roles sent from the authorization header and if mapped with some roles, the access is granted`

Are the roles listed in the kibana WebUI only roles.yaml, or registered via REST API?
 `It should also show roles registered with rest apis`

Also, Is it possible to get rolemapping via LDAP?
`It can be done with the help of backend role, you can follow process specified here - https://aws.amazon.com/blogs/opensource/ldap-integration-for-open-distro-for-elasticsearch/`

**Comment by palashhedau** [comment]
Please feel free to reopen the issue in case if you have more question.
