### ISSUE TITLE
Allow Opendistro Security to be disabled temporarily via API

### ISSUE THREAD

**Issue by bharadwajrembar** [opendistro-for-elasticsearch/security#299]
Right now in order to disable security, we follow: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/disable/ which is tedious as it has to be done on all of the nodes. Could you please come up with a way to disable it via an API call just so it helps cases where one might be need to temporarily disable just for testing?

Maybe something like `POST _opendistro/_security/_enable` or `POST _opendistro/_security/_disable`. Of course, you do need to authenticate against ODFE to disable it.

**Comment by cliu123** [comment]
@bharadwajrembar According to the [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/disable/#disable-security)
Adding `opendistro_security.disabled: true` in the elasticsearch.yml file and restart cluster&nodes will disable security plugin.

**Comment by hardik-k-shah** [comment]
Changing security posture (enable/disable security) of the distributed system like Elasticsearch should not be done through APIs due to risk associated with it. To modify security posture entirely (like enable/disable), one should have access to physical machine itself.
