### ISSUE TITLE
Versioning ODFE documentation

### ISSUE THREAD

**Issue by sandeepkanabar** [opendistro-for-elasticsearch/security#300]
Currently, there's no versioning mechanism in ODFE documentation and hence no way to refer documentation specific to older version e.g. say `0.10.0.0`. If someone wants to get started with an older version, then steps to install and get started easily aren't there as well. 

Can we introduce versioning in ODFE documentation at https://opendistro.github.io/for-elasticsearch-docs/. 

Thoughts? @debjanibnrj @hardik-k-shah ?

**Comment by vrozov** [comment]
Please open a new issue in the ODFE docs repo: https://github.com/opendistro/for-elasticsearch-docs
