### ISSUE TITLE
OD Not working with Basic Elastic version

### ISSUE THREAD

**Issue by chelambarasan** [opendistro-for-elasticsearch/security#305]
Hi Team,

OD has great security features and we want to use that with basic version of ES for getting a few more great features like automatic index management. But currently we are running into the issue on installing the Security plugin on Basic Elastic version:

Elastic Version: 7.2.0(Basic)
OD version: 1.2.0

java.lang.IllegalArgumentException: Cannot have additional setting [http.type] in plugin [opendistro_security], already added in plugin [x-pack-security]
        at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:215) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.node.Node.<init>(Node.java:308) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.2.0.jar:7.2.0]

On digging a bit into the code, it seems that OD is trying to update http.type as 

(NetworkModule.HTTP_TYPE_KEY, "com.amazon.opendistroforelasticsearch.security.ssl.http.netty.OpenDistroSecuritySSLNettyHttpServerTransport");

https://github.com/opendistro-for-elasticsearch/security-ssl/blob/cb68c0707fefa2f52e1751b3a8bdd162a20a3775/src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java#L371

But looks the Basic Version of ES has http.type set as http.type.default in the network module as per below 

https://github.com/elastic/elasticsearch/blob/26b9cf787dfcfb2340fd2dbc98e4c42faf868e40/server/src/main/java/org/elasticsearch/common/network/NetworkModule.java#L69

It would be great if this can be fixed so that users can avail of best of both the worlds.

**Comment by DmitryOlshansky** [comment]
Simply delete modules/x-pack-security and you should be good to go.

**Comment by chelambarasan** [comment]
Thanks @DmitryOlshansky . Elastic coming up after deleting the x-pack security module. But seeing some error like

 [2020-03-22T06:42:56,855][ERROR][c.a.o.s.a.s.SinkProvider ] [es-1-897576757] Default endpoint could not be created, auditlog will not work properly.

Will this have any impact on audit logging feature by OD?

**Comment by chelambarasan** [comment]
Hi  @DmitryOlshansky, Similarly if I try to use Kibana Basic with OD security kibana plugin installed, Getting same kind of error. Can you let me know what changes needed in kibana

{"type":"log","@timestamp":"2020-03-25T11:18:13Z","tags":["fatal","root"],"pid":13644,"message":"{ Error: cluster 'security' already exists\n    at Object.server.expose (/usr/share/kibana/src/legacy/core_plugins/elasticsearch/index.js:75:17)\n    at createCluster (/usr/share/kibana/x-pack/server/lib/get_client_shield.js:13:41)\n    at /usr/share/kibana/node_modules/lodash/index.js:7407:25\n    at getUserFn (/usr/share/kibana/x-pack/plugins/reporting/server/lib/get_user.js:11:33)\n    at call (/usr/share/kibana/x-pack/plugins/reporting/server/lib/once_per_server.js:30:15)\n    at memoized (/usr/share/kibana/node_modules/lodash/index.js:7956:27)\n    at Object.authorizedUserPreRoutingFn (/usr/share/kibana/x-pack/plugins/reporting/server/routes/lib/authorized_user_pre_routing.js:14:19)\n    at Object.call (/usr/share/kibana/x-pack/plugins/reporting/server/lib/once_per_server.js:30:15)\n    at Object.memoized [as authorizedUserPreRoutingFactory] (/usr/share/kibana/node_modules/lodash/index.js:7956:27)\n    at Object.authorizedUserPreRoutingFactory [as getRouteConfigFactoryReportingPre] (/usr/share/kibana/x-pack/plugins/reporting/server/routes/lib/route_config_factories.js:14:68)\n    at Object.getRouteConfigFactoryReportingPre [as registerGenerate] (/usr/share/kibana/x-pack/plugins/reporting/server/routes/generate.js:15:53)\n    at registerGenerate (/usr/share/kibana/x-pack/plugins/reporting/server/routes/index.js:47:16)\n    at Plugin.init [as externalInit] (/usr/share/kibana/x-pack/plugins/reporting/index.js:182:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  isBoom: true,\n  isServer: true,\n  data: null,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/generalError' }"}

**Comment by DmitryOlshansky** [comment]
As far as Kibana goes - disable xpack security and spaces. Then it should start normally.

**Comment by chelambarasan** [comment]
Thanks @DmitryOlshansky . Kibana is working fine with above changes.
Getting some issues with Audit logging for Basic ES as which is not coming in OSS version

{"type": "server", "timestamp": "2020-04-01T12:41:45,368+0000", "level": "ERROR", "component": "c.a.o.s.a.BackendRegistry", "cluster.name": "test-stg", "node.name": "node-1-8975762323757", "cluster.uuid": "W6RVWhVJRJ68eapZiw", "node.id": "UQJQcHthS4Kz1w",  "message": "Not yet initialized (you may need to run securityadmin)"

Tried Running the security admin which is also working fine for OSS but getting some error for Basic

ERR: Seems you use a node certificate which is also an admin certificate
     That may have worked with older Open Distro Security versions but it indicates
     a configuration error and is therefore forbidden now.
Unable to check whether cluster is sane
ERR: An unexpected ElasticsearchSecurityException occured: No user found for cluster:monitor/nodes/info
Trace:
ElasticsearchSecurityException[No user found for cluster:monitor/nodes/info]

Can you please let me know if i miss anything?

**Comment by DmitryOlshansky** [comment]
What it says - admin certificate and node certificate got to be 2 different certificates and keys respectively.

**Comment by chelambarasan** [comment]
Yes. This issue was not coming in OSS but got it in Basic. So created 2 certificates and keys. tried running the securityadmin and got the below error

ERR: Seems you use a node certificate which is also an admin certificate
That may have worked with older Open Distro Security versions but it indicates
a configuration error and is therefore forbidden now.
Unable to check whether cluster is sane
ERR: An unexpected ElasticsearchSecurityException occured: No user found for cluster:monitor/nodes/info
Trace:
ElasticsearchSecurityException[No user found for cluster:monitor/nodes/info]

**Comment by chelambarasan** [comment]
@DmitryOlshansky ,

Audit logging is not written in logs file. Can you check below whether am i missing anything? Thanks

After enabling audit logging in elasticsearch.yml, 

opendistro_security.audit.type: log4j
opendistro_security.audit.config.log4j.logger_name: es_audit
opendistro_security.audit.config.log4j.level: INFO
opendistro_security.audit.enable_rest: true
opendistro_security.audit.enable_transport: true
opendistro_security.audit.ignore_users: NONE

tried the below option in log4j2.properties

appender.audit_logging_rolling.type = RollingFile
appender.audit_logging_rolling.name = audit_logging_rolling
appender.audit_logging_rolling.fileName = ${sys:es.logs.base_path}${sys:file.separator}es_audit.json
appender.audit_logging_rolling.layout.type = PatternLayout
appender.audit_logging_rolling.layout.type_name = audit_logging

appender.audit_logging_rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}es_audit-%d{yyyy-MM-dd}-%i.json
appender.audit_logging_rolling.policies.type = Policies
appender.audit_logging_rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.audit_logging_rolling.policies.size.size = 256MB
appender.audit_logging_rolling.strategy.type = DefaultRolloverStrategy
appender.audit_logging_rolling.strategy.max = 5



logger.audit_logging.name = com.amazon.opendistroforelasticsearch.security 
logger.audit_logging.level = info 
logger.audit_logging.appenderRef.audit_logging_rolling.ref = audit_logging_rolling 
logger.audit_logging.additivity = false

**Comment by yoke88** [comment]
@DmitryOlshansky can i just disable x-pack security just in the elasticsearch yaml configuration file and do not delete modules/x-pack-security ?

**Comment by pbhalera** [comment]
I faced same issue as not able to initialize security plugin when x-pack-security module is present. Is there easy way to use security plugin along with disabling xpack.security in elasticsearch.yaml

**Comment by yoke88** [comment]
@pbhalera  Hi ,here is my necessory configuration for elasticsearch kibana and beats, it works in my environment with ELK basic llicense + opendistro security plugin

### elasticsearch + es opendistro security plugin 
``` yaml
xpack.security.enabled: false

```

### kibana + kibana opendistro security plugin 
``` yaml
# x-pack security is replaced by opendistro security
xpack.security.enabled: false

# space is replaced by opendistr security multi tenant
xpack.spaces.enabled: false

```

### beats

``` yaml
# x-pack ilm seems need some feature of x-pack security 
setup.ilm.enabled: false 
```

**Comment by yoke88** [comment]
if you want setup.ilm work,  and do not include a setting `setup.ilm.enbaled:false`,you need sign logstash user more permissions, or using a high priviledge account and setup ilm manully

if `setup.ilm.enabled:false` was enabled in beats configuration file , beats will generate many more daily created indexes , which impact the performance of ES cluster.

below is a role copy from logstash role and add permissions which ilm need
```
{
  "description": "Provide the minimum permissions for logstash and beats",
  "index_permissions": [
    {
      "index_patterns": [
        "*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "indices:admin/aliases/exists",
        "indices:admin/aliases/get"
      ]
    },
    {
      "index_patterns": [
        "logstash-*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "crud",
        "create_index",
        "manage",
        "manage_aliases"
      ]
    },
    {
      "index_patterns": [
        "*beat*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "crud",
        "create_index",
        "manage",
        "manage_aliases"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": [
    "cluster_monitor",
    "cluster_composite_ops",
    "ODS_CLUSTER_READ_ILM",
    "indices:admin/template/get",
    "indices:admin/template/put",
    "cluster:admin/ingest/pipeline/put",
    "cluster:admin/ingest/pipeline/get",
    "cluster:admin/ilm/put"
  ]
}
```

**Comment by lukasmrtvy** [comment]
@yoke88: is it ok to run opendistro security plugin in non os version of elasticseach/kibana ( basic ) ? Or is it agains licence and thus not possible to use in enterprise ? thanks

**Comment by vrozov** [comment]
@lukasmrtvy It is OK to run security plugin on any ES version that you have license for and that is compatible with the security plugin (x-pack is not compatible).
