### ISSUE TITLE
Exit with Read-only file system for certificates 

### ISSUE THREAD

**Issue by jeff-cook** [opendistro-for-elasticsearch/security#32]
I would expect odfe does not edit certificates and keys. 

Running 0.8.0 image

The container closes with the following log if it can't write to the files.
```
Basedir: /usr/share/elasticsearch
 Elasticsearch install type: rpm/deb on CentOS Linux release 7.6.1810 (Core) 
 Elasticsearch config dir: /usr/share/elasticsearch/config
 Elasticsearch config file: /usr/share/elasticsearch/config/elasticsearch.yml
 Elasticsearch bin dir: /usr/share/elasticsearch/bin
 Elasticsearch plugins dir: /usr/share/elasticsearch/plugins
 Elasticsearch lib dir: /usr/share/elasticsearch/lib
 Detected Elasticsearch Version: x-content-6.6.2
 Detected Open Distro Security Version: 0.8.0.0
 tee: /usr/share/elasticsearch/config/esnode-key.pem: Read-only file system
```
How can I keep it from trying to modify them?

Thank you

**Comment by vnil1994** [comment]
@jeff-cook Did you solve this? We're having the same problem

**Comment by symfrog** [comment]
This typically occurs if you have not yet configured security in `elasticsearch.yml` as described in the "Edit elasticsearch.yml to Add Your Certificates" section [here](https://aws.amazon.com/blogs/opensource/add-ssl-certificates-open-distro-for-elasticsearch/). 

[During startup](https://github.com/opendistro-for-elasticsearch/security/blob/dfc41db0d0123cd0965d40ee47d61266e560f7e6/tools/install_demo_configuration.sh#L194) open distro will check for the presence of settings starting with `opendistro_security` in `elasticsearch.yml` and will exit without modifying the keys or `elasticsearch.yml` if found. @jeff-cook @vnil1994

**Comment by jeff-cook** [comment]
Updating the `elasticsearch.yml`  file, even with matching file names, did resolve the issue.
