### ISSUE TITLE
Question: Is it strictly required to use the OSS release for standalone plugins?

### ISSUE THREAD

**Issue by Ricaz** [opendistro-for-elasticsearch/security#329]
I have a 3-node cluster running `elasticsearch-7.5.2` and I'm wondering if I can use the security plugin, or if I need to replace them with `elasticsearch-oss 7.5.2`.

And if so, does anyone know if you can easily swap out the package?

I built the plugin myself and it seems to install OK, but I'm hesitant to fully deploy it.

**Comment by hardik-k-shah** [comment]
We develop, build and test using OSS version only and recommend to use OSS. 
There may be some work around community might have figured out to work with non-OSS. There is some similar discussion here: https://github.com/opendistro-for-elasticsearch/security/issues/305
