### ISSUE TITLE
Is Open Distro compatible with the Transport Client?

### ISSUE THREAD

**Issue by alexmorosmarco** [opendistro-for-elasticsearch/security#331]
I do not find any documentation at all about **[the Java Transport Client](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/java-clients.html)** in the Open Distro documentation, but that does not necessarilly mean it is not supported. 😉 

I have 2 questions regarding it:

1. Is Open Distro compatible with **the Java Transport Client**? Can we use it?
2. If it is supported in Open Distro, then
    1. what are the **`elasticsearch.yml` configuration properties** I should configure to enable it?
    2. are the **Java Transport Client configuration properties** the same ones that the official Elasticsearch supports?

Thanks!

**Comment by vrozov** [comment]
It is not supported. Please see #305 for details.

**Comment by alexmorosmarco** [comment]
Actually that other does not talk about the Java Transport client?

*--*
*Alex Moros Marco*

**Comment by vrozov** [comment]
Java Transport client requires X-Pack and X-Pack is not supported.

**Comment by alexmorosmarco** [comment]
The Java Transport client can be used against an Open Source cluster (seen this in the Elasticsearch forum).
I guess the Open Distro is a fork of the open source version of Elasticsearch right?

So at the end I think we have the following:

- **if you do not care about security for some reason**, **I guess you can** use the Java Transport Client against Open Distro.
- **if you do care about security** I understand **it is not possible** as the security is included in Basic version of Elasticsearch, not in the Open Source version.

@vrozov do you aggree?

**Comment by alexmorosmarco** [comment]
@vrozov sorry to insist, do you aggree on my last comment?

**Comment by vrozov** [comment]
Open Distro for Elasticsearch is not a fork, it is a binary distribution that includes Elasticssearch open source as one of the components (https://opendistro.github.io/for-elasticsearch-docs/).

This GitHub repository is dedicated for the opendistro security plugin and does not cover generic support/compatibility issues of the Elasticssearch OSS distribution. With the security plugin enabled, the Java Transport Client is **not** supported. With the security plugin disabled, the Java Transport Client may work, but you will need to confirm this with the Elasticsearch OSS. Even if the Java Transport Client happens to work with the current ODFE version, the future compatibility is not guaranteed.

**Comment by alexmorosmarco** [comment]
Thanks I just learned that today in [the FAQ of Open Distro](https://opendistro.github.io/for-elasticsearch/faq.html):
>**Are you forking Elasticsearch?**
>
>No. Open Distro for Elasticsearch is not a fork. In fact, we intend to continue making contributions to the Apache 2.0-licensed Elasticsearch code. Our goal is to ensure that open source Elasticsearch continues to thrive.

Thanks about this answer, as I want the security plugin enabled of course:
>With the security plugin enabled, the Java Transport Client is not supported.

Thanks!
