### ISSUE TITLE
Too large Cookie when using JWT Auth

### ISSUE THREAD

**Issue by dixiekong0** [opendistro-for-elasticsearch/security#374]
Hey, we are using:

```
amazon/opendistro-for-elasticsearch:1.4.0
amazon/opendistro-for-elasticsearch-kibana:1.4.0
```
We configured Kibana to pass a JSON Web Token (provided as GET param to Kibana) to ES for authenticate users. Setup first worked perfectly well using development JWTs, however we encountered errors using the setup in production, as we are provided with larger Tokens, that may result in a larger authentication cookie which may be too large for the browser to accept.

To our best knowledge the following seems to happen:

1. Browser initially calls Kibana providing JWT via GET param
2. Kibana responds and tries to set Cookie: `security_authentication=Fe26.2** .... (4325) bytes long` (too larger for FF and Chrome, having 4096 as limit)
3. Browser requests required ressources (i.e. bootstrap.js, etc.) but request fails due to missing authenticaion cookie.

Would be really nice if someone could take a look at this :)

Greetings!

**Comment by dinusX** [comment]
Hi dixiekong0 ,

Were you able to solve this issue ?

If not, did you check what data are you passing in jWT that is causing the Cookie to become large ?

**Comment by fortran01** [comment]
In our scenario, it was the ID Token that was overloaded.

**Comment by debjanibnrj** [comment]
Hi, security authentication cookie size is currently limited by the browser. Both *RFC* 2109 and *RFC* 6265 state that user agents should support *cookies* of at least 4096 bytes. For many browsers this is also the maximum size of the cookie.

We are working on solution for this use case. Meanwhile a workaround for JWT/SAML is to limit the number of roles and sttributes being send from the IdP.

**Comment by debjanibnrj** [comment]
I will track this issue under https://github.com/opendistro-for-elasticsearch/security/issues/375 as both are referencing the same problem.
