### ISSUE TITLE
LDAP/AD authentication issue

### ISSUE THREAD

**Issue by anukalady** [opendistro-for-elasticsearch/security#378]
We have set up the authc and authz on OSS 7.6 with OD1.6 cluster 

Authorization:
rolebase: < DN for AD Group >  ( works fine )
Authentication:  
Userbase: < DN for a Container/OU >   ( works fine )

Authorization is being handled by an AD Group, is working fine.  However, we are looking for a possibility  to confine authentication for users by  membership of a  certain AD Group. We don’t see any option to provide AD Group, to allow only members of that AD Group to login.
 
 When <DN for Container/OU> provided for Userbase in  authentication section. App login is being accepted for every user in the subtree of the same container/OU  which is not desired for authentication access . In our domain we have users created in various containers and OU's . Pooling only required users for authentication is what we are looking for. 

Can OD development team suggest some parameters to configure in the config.yml so as to confine the authentication LDAP query hit a AD group defined in the userbase?

Any threads much appreciated

**Comment by vnil1994** [comment]
Can we open this? I have the exact same issue, described here: https://discuss.opendistrocommunity.dev/t/authentication-via-ldap-only-allow-certain-security-groups/4540

Is there not a way to restrict the authentication to a security group in the AD, instead of setting a OU?
