### ISSUE TITLE
audit not working for e.g. delete index or query index ... only for failed login 

### ISSUE THREAD

**Issue by mato69** [opendistro-for-elasticsearch/security#380]
Hi, 

this is one question from opendistro forum (user: Xyrion): 
I have a scenario where I need to record if an admin deletes an index or a record from an index. Is this possible? I enabled the opendistro audit and tested to delete an index but it didn’t show up in my esaudit index. I can however see data flowing in to the esaudit in relation to Transport SSL, meaning the audit functionality is working.

I setup audit with the following config:
opendistro_security.audit.type: internal_elasticsearch
opendistro_security.audit.config.index: “'esaudit-'YYYY.MM.dd”
opendistro_security.audit.ignore_users: NONE
Is there additional config that I can add to track what the users does once they have authenticated.
Additional info: I used a simple curl with the -u to delete the index.

my case (user: mato69) is similar, we want (if it's possible) to have records/log for access, query, delete index and so on ... this is our elasticsearch.yml:
...
opendistro_security.audit.enable_transport: true
opendistro_security.audit.resolve_bulk_requests: true
opendistro_security.audit.enable_rest: true
#opendistro_security.audit.enable_request_details: true
opendistro_security.audit.log_request_body: true
opendistro_security.audit.resolve_indices: true
...
opendistro_security.audit.enable_request_details is not working so it's #

**Comment by mato69** [comment]
for others with my problem, finally i went with  https://www.elastic.co/blog/monitoring-the-search-queries ssl from client browser to kibana and then clear http from kibana to elasticsearch (same server). Packetbeat, max message 20k.

**Comment by sujithvm** [comment]
@mato69 Currently audit logging of document deletion in an index is supported. 
Please specify the index that you want to monitor for doc writes using 

```
opendistro_security.compliance.history.write.watched_indices: ["name-of-index"]
```

**Comment by sujithvm** [comment]
There is new category "INDEX_EVENT" logged on transport layer and all "indices:admin/*" events will be logged including "indices:admin/delete". Please check v1.9.0.1 release
