### ISSUE TITLE
Audit - tracking users deleting index

### ISSUE THREAD

**Issue by Xyrion** [opendistro-for-elasticsearch/security#381]
Hello,

I have a scenario where I need to record if an admin deletes an index or a record from an index. Is this possible? I enabled the opendistro audit and tested to delete an index but it didn’t show up in my esaudit index. I can however see data flowing in to the esaudit in relation to Transport SSL, meaning the audit functionality is working.

I setup audit with the following config:

opendistro_security.audit.type: internal_elasticsearch
opendistro_security.audit.config.index: “'esaudit-'YYYY.MM.dd”
opendistro_security.audit.ignore_users: NONE

Is there additional config that I can add to track what the users does once they have authenticated.

Additional info: I used a simple curl with the -u to delete the index.

Thanks for any help!

**Comment by sujithvm** [comment]
Currently doc deletion in an index is supported. 
Please specify 

```
opendistro_security.compliance.history.write.watched_indices: ["name-of-index"]
```

You should be able to see an `COMPLIANCE_DOC_WRITE` event with audit message having attribute `audit_compliance_operation` as DELETE

**Comment by sujithvm** [comment]
There is new category "INDEX_EVENT" logged on transport layer and all "indices:admin/*" events will be logged including "indices:admin/delete". Please check v1.9.0.1 release

**Comment by Xyrion** [comment]
@sujithvm Could you please share the config to setup this audit feature?
