### ISSUE TITLE
How to enable JWT Authenticator on OpenDistro in my AWS Elasticsearch cluster?

### ISSUE THREAD

**Issue by lucastex** [opendistro-for-elasticsearch/security#382]
Hi all!

We're migrating our app from Elastic Cloud to AWS ElasticSearch, and will use the OpenDistro security features! We've used opendistro with JWT auth locally, but after launching one cluster in AWS Elasticsearch, we haven't found any way to enanle the jwt authenticator on it. As you can see in the attached images, only http basic auth is enabled (the default installation)

How can we enable it, and configure our JWT secret? This is achieved by editing the config.yml opendistro security plugin. - https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/configuration/#json-web-token

Thank you

<img width="506" alt="Screen Shot 2020-04-16 at 10 53 35" src="https://user-images.githubusercontent.com/52998/79465962-5b4f3a00-7fd2-11ea-9da6-94a862ddca6a.png">
<img width="798" alt="Screen Shot 2020-04-16 at 10 53 41" src="https://user-images.githubusercontent.com/52998/79465972-5db19400-7fd2-11ea-8956-4fe9b5801bec.png">

**Comment by palashhedau** [comment]
Hi @lucastex 

Did you try using the 
https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#update-configuration

The configuration present in config is reflected in this api result and can be updated as per need. 

Let me know if anything else is required or you are having problem configuring it.

**Comment by sakuratw** [comment]
It works only for the elastic part, as for kibana it will not be possible as you can t use the 'authorization' header so you ll need a custom one and you ll need to modify the kibana.yml but unfortunately we will not be able to do it through aws.

**Comment by vrozov** [comment]
Please consult AWS Elastic search documentation and route questions to AWS Elastic search forums and technical support. Open Distro for Elasticsearch is not necessarily equal in functionality with AWS Elasticsearch and what is supported/provided by AWS Elasticsearch may be not supported by ODFE and vise versa.

**Comment by cruizba** [comment]
@sakuratw I'm having exactly the same problem. Did you figured out something?

**Comment by sakuratw** [comment]
unfortunately, for now you will need to install a separate Kibana to be able to customize the configuration

**Comment by vrozov** [comment]
@cruizba @sakuratw Please check with AWS Elasticsearch team on what is supported by AWS to avoid any misleading information.
