### ISSUE TITLE
Dev Tools History does not persist sessions

### ISSUE THREAD

**Issue by nicot007** [opendistro-for-elasticsearch/security#385]
We’ve noticed with ES 6.7 and OD 0.9
We have Security Plugin in both ES and Kibana

Our dev tools page does not save the commands after logging out.
Instead we are welcomed to the “Welcome To Console Page>Get to Work” Every time one logs in.

My Kibana YML
------------ Basic Server/ES Information ------------------
server.port: 443
server.host: xxx
elasticsearch.url: xxx
elasticsearch.username: xxx
elasticsearch.password:

------------ Server SSL ------------------
server.ssl.enabled: true
server.ssl.certificate: /xxx
server.ssl.key: /xxx
server.ssl.supportedProtocols: [‘TLSv1.1’, ‘TLSv1.2’]

------------ Elasticsearch SSL ------------------
elasticsearch.ssl.certificateAuthorities: “/xxx”
elasticsearch.requestHeadersWhitelist: [“securitytenant”,“Authorization”]

------------ Debugging Settings --------------
logging.dest: xxx/kibana.stdout

**Comment by ycyr** [comment]
Hi @alolita, this issue seems to be related to the clearing of the local storage on browser when we are logging off. Take a look at [my comment ](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/118#issuecomment-614897218).

**Comment by hardik-k-shah** [comment]
Closing issue here.
Related issue on Kibana repo: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/118
