### ISSUE TITLE
Kibana_read_only is not really readonly, and please help to create a kibana_user_ro role

### ISSUE THREAD

**Issue by yoke88** [opendistro-for-elasticsearch/security#394]
The internal kibana_read_only role makes kibana user only see the dashboards tab and can not edit the dashboard （ but this protection is only work when user is using kibana), if the user belongs kibana_user and kibana_read_only roles ,it can delete indexes about kibana by using Elasticsearch API.

so i decide to copy kibana_user role to kibana_user_ro , and changed the permission of indexes about kibana to read only . if i add a user to this kibana_user_ro role only, the user can not see any dashboards and there is some error in chrome dev tools.

![error](https://user-images.githubusercontent.com/3146226/79832140-5c6dd600-83db-11ea-9ab9-a9c684c8d3bd.JPG)

The customized  kibana_user_ro role definition

```json
{
  "description": "Provide the minimum permissions for a kibana user",
  "index_permissions": [
    {
      "index_patterns": [
        ".kibana",
        ".kibana-6",
        ".kibana_*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read"
      ]
    },
    {
      "index_patterns": [
        ".tasks",
        ".management-beats",
        "*:.tasks",
        "*:.management-beats"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": [
    "cluster_composite_ops_ro"
  ]
}
```

please give a help to make this work , thanks

**Comment by yoke88** [comment]
and are there documents to explian the  role definition below?

![image](https://user-images.githubusercontent.com/3146226/79833672-5d543700-83de-11ea-962e-e85f1ab8e60f.png)

**Comment by yoke88** [comment]
Even copy the kibana_user role  to kibana_user_ro and do not change any thing ,then add new user to kibana_user_ro role and allread role, the new user can not see any dashboard. if i add the new user to kibana_user role and allread role ,the dashboard shows there . is something else hardcode and i need to change by editing kibana.yml file ?

![截图_2020-04-21_19-27-00](https://user-images.githubusercontent.com/3146226/79860991-3873ba00-8406-11ea-9715-d003d2dd1bfc.png)

**Comment by palashhedau** [comment]
is user has kibana_user and kibana_read_only role, he is able to delete the indices as it has Kibana_user role.


so i decide to copy kibana_user role to kibana_user_ro , and changed the permission of indexes about kibana to read only . if i add a user to this kibana_user_ro role only, the user can not see any dashboards and there is some error in chrome dev tools. -> I am able to see dashboard tab saying I do not have any dashboard at the present. Which version of Opendistro you are using? I am using 
opendistro-1.4. Also I do not have any errors in console.

**Comment by yoke88** [comment]
opendistro 1.6 and 1.7

**Comment by palashhedau** [comment]
It looks like after copying the kibana_user role to kibana_user_ro the global tenant is not available to the user and hence no data is available to the user and so the dashboard.

Please assign the global tenant permission to the kibana_user_ro explicitly and make sure user is using global tenant in multitenancy tab.

<img width="1112" alt="Screen Shot 2020-06-05 at 11 16 12 AM" src="https://user-images.githubusercontent.com/31803654/83909695-1ddb7300-a71e-11ea-8d71-1cad83bbdf5f.png">

I am closing this ticket, please feel free to reopen in case of more questions/issues

**Comment by yoke88** [comment]
i have tried your suggestion, it seems works. but i found another two problems.

1.  the global_tenant become false  and the private tenant for user is true,even  the user belong to kibana_user, who have permission to save dashboard or query, but i always got a 403 error says no  no permissions for [indices:data/write/index] when saving a query.

2. kibana_read_only role seems no effect now. if  a user belongs to kibana_user and kibana_read_only ,  i just can see two tabs and the dashboards is readonly when i use opendistro security 1.6.x ,but now in 1.7 , it seems no effect.

**Comment by yoke88** [comment]
kibana_user_ro

``` json

{
  "description": "Provide the minimum permissions for a kibana user",
  "index_permissions": [
    {
      "index_patterns": [
        ".kibana",
        ".kibana-6",
        ".kibana_*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read"
      ]
    },
    {
      "index_patterns": [
        ".tasks",
        ".management-beats",
        "*:.tasks",
        "*:.management-beats"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "read"
      ]
    }
  ],
  "tenant_permissions": [
    {
      "tenant_patterns": [
        "global_tenant",
        "*global*"
      ],
      "allowed_actions": [
        "kibana_all_read"
      ]
    },
    {
      "tenant_patterns": [
        "global_tenant"
      ],
      "allowed_actions": [
        "kibana_all_read"
      ]
    }
  ],
  "cluster_permissions": [
    "cluster_composite_ops_ro"
  ]
}
```

but the global_tenant is false 

![image](https://user-images.githubusercontent.com/3146226/84121288-8baed400-aa69-11ea-9ab8-2fde6b58d09d.png)
