### ISSUE TITLE
opendistro_security.allow_default_init_opendistrosecurityindex should be opendistro_security.allow_default_init_securityindex

### ISSUE THREAD

**Issue by cdengatgithub** [opendistro-for-elasticsearch/security#41]
in the elasticsearch.ym.sample opendistro_security.allow_default_init_opendistrosecurityindex should be opendistro_security.allow_default_init_securityindex.

**Comment by cdengatgithub** [comment]
sorry, in the elasticsearch.yml.example advance setting part.

**Comment by hardik-k-shah** [comment]
Thanks for reporting. 
I have created a pull request for fixing this typo.
