### ISSUE TITLE
Security URI issue

### ISSUE THREAD

**Issue by surajrrao** [opendistro-for-elasticsearch/security#411]
I am using OpenDistro Security Plugin 0.9.0 - and seeing Kibana is calling /_opendistro/_security/api/config endpoint instead _opendistro/_security/api/securityconfig

Due to this LDAP authentication & authorization is not working.

Need immediate help on this!

**Comment by vrozov** [comment]
Please provide details (for example steps to reproduce, is it reproducible only with Kibana, etc) explaining why do you think that this is a security plugin issue.

> Need immediate help on this!

The help is provided by the Opendistro for Elasticsearch community without any SLA guarantee. We will try to respond to all reported issues as time permits.

**Comment by dinusX** [comment]
Feel free to re-open the issue after you provide more context. 
Closing it due to inactivity
