### ISSUE TITLE
Move elasticsearch.version from individual plugins to parent pom

### ISSUE THREAD

**Issue by lukas-vlcek** [opendistro-for-elasticsearch/security#412]
I would suggest moving `elasticsearch.version` property from individual plugins (like [here](https://github.com/opendistro-for-elasticsearch/security-advanced-modules/blob/v0.10.0.1/pom.xml#L37) for advanced security) to this parent pom. This will simplify version management and reduce risk of error.

**Comment by sujithvm** [comment]
We have consolidated all the security repos (security, security-parent, security-advanced-modules, security-ssl) into security project. 

The only place where elasticsearch version needs to be updated is https://github.com/opendistro-for-elasticsearch/security/blob/master/pom.xml#L71
