### ISSUE TITLE
Unable to Aditlog - Document Read

### ISSUE THREAD

**Issue by vmahesh22** [opendistro-for-elasticsearch/security#413]
I have enabled 'advanced_modules_enabled' using below property in elasticsearch.yml file.
opendistro_security.advanced_modules_enabled: true

I tried with search/delete operations on other indexes but nothing is logging in to security-auditlog* index. (fyi, logged into admin/admin user)

let me know if I missed any configuration to log document read/write operations

**Comment by sujithvm** [comment]
@vmahesh22 
Please share your elasticsearch.yml configuration relevant to audit logging.
 
Ensure storage type for audit logging is set to internal_elasticsearch if you want the logs to be posted an index. 

https://opendistro.github.io/for-elasticsearch-docs/docs/security-audit-logs/storage-types/ 

Let me know if you are facing any issues

**Comment by sujithvm** [comment]
Please re-open if you are still facing any issues
