### ISSUE TITLE
Common Certificate with Multiple SAN 

### ISSUE THREAD

**Issue by shahbhavin** [opendistro-for-elasticsearch/security#414]
Java: 1.8.0_211
OpenDistry Security: 0.9.0.0
ElasticSearch:6.7.1

I have certificate with multiple different SAN (Subject Alternative Name) in it. SAN has multiple host name as Certificate has to be shared among hosts. 

When we do SSL configuration in opendistro-security; It does not recognize / respect other than CN for the trust.  Expectation is that it should consider all the CN/SAN for the trust. 

Reason: Do not want to manage hundreds of certificates & also do not want to have trouble of having common wildcard certificates so require SAN.

Is this correct expectation. I can help if this has to be solved.

**Comment by debjanibnrj** [comment]
Hi @shahbhavin,

Thanks for your question. ODFE Security verifies the TLS certificates you use against the Root and Intermediate CA's. If you enable the `opendistro_security.ssl.transport.enforce_hostname_verification` option we verify that the hostname of the communication partner matches the hostname in the certificate. The hostname is taken from the subject or SAN entries of your certificate. 

For more details refer to - `https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/tls/#advanced-hostname-verification-and-dns-lookup`

Let me know if this is still an issue for you.
