### ISSUE TITLE
Anonymous user for Kibana and ElasticSearch

### ISSUE THREAD

**Issue by dlumbrer** [opendistro-for-elasticsearch/security#42]
Hi everyone,

Is it possible to have an anonymous user that can access to Kibana and ElasticSearch (using READ permissions to some indices) without login?

thanks!

**Comment by hardik-k-shah** [comment]
HI @dlumbrer,

Yes, It is possible.  

To enable anonymous access, you have to enable anonymous access in config.yml and kibana.yml. You also have to create one role for anonymous access with related permission (read permission to some indices in your case) and related role mapping for anonymous user. 
Anonymous requests always assigned with opendistro_security_anonymous as username and  opendistro_security_anonymous_backendrole as backend role. 

Detailed steps to enable anonymous access: 
1) In config.yml enable anonymous access 
```
opendistro_security:
    dynamic:
       http:
          anonymous_auth_enabled: false
```
2) Create anonymous role with required permission. ( you can create this role either through kibana.yml or through changing roles.yml) 
for ex:, 
```
opendistro_security_anonymous:
readonly: true
cluster:
  - CLUSTER_COMPOSITE_OPS_RO
indices:
  '*':
    '*':
      - READ
```
3) Create role mapping for opendistro_security_anonymous_backendrole role. 
```
opendistro_security_anonymous:
backendroles:
  - opendistro_security_anonymous_backendrole
```
4) Use securityadmin tool to apply this config changes if your cluster is already up and running. 
5) Update kibana.yml to enable anonymous access for kibana. You have to restart kibana process to apply this changes. 
```
opendistro_security.auth.anonymous_auth_enabled: true
```

**Comment by hardik-k-shah** [comment]
Please re-open this issue if you have further questions.

**Comment by ssanchezjoss** [comment]
HI @hardik-k-shah how are you. I followed these steps in OpenDistro 1.6.0 but it tells me that 
**read_only** is not a valid parameter. Should I use **reserved** and **hidden** instead ??
Also,  shouldnt this anonymous_auth_enabled: false should be  anonymous_auth_enabled: **true**  ??
Thank you very much :)

**Comment by hardik-k-shah** [comment]
@ssanchezjoss 

```readonly: true```  is 6.x configuration. 

For 7.x it should be ```reserved: true```

And yes anonymous_auth_enabled should be true. 
```anonymous_auth_enabled: true```

Thanks for pointing our. I have updated it.
