### ISSUE TITLE
Security config files overwritten during upgrade

### ISSUE THREAD

**Issue by rlk5546** [opendistro-for-elasticsearch/security#43]
Upgrading from 6.5.4 (ODFE 0.7) to 6.6.2 (ODFE 0.8), the config files in /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/ were overwritten to defaults.

After restoring my admin and kibanaserver passwords from backup in internal_users.yml, and restoring my authc and authz sections in config.yml, the upgrade to 0.9 became available.

Upgrading to 6.7.1 (ODFE 0.9) overwrites my opendistro_security/securityconfig/ files again!

I don't believe an upgrade should be overwriting this directory.  Best suggestion is to use a copy of this directory when executing _securityadmin.sh_ so that customization's are persistent between upgrades.  If agreeable this tip should be included in documentation.  If it already is, I missed it.

Tx!

rlk

**Comment by viswasou** [comment]
@rlk5546 Are you using a docker distribution? 

We do not support in place upgrades at this time, adding a feature request for this. The best way today (not the ideal experience) is create a snapshot and restore from it on the new cluster.

**Comment by hardik-k-shah** [comment]
yml configs are for first time bootup only. Once your cluster is up and running all configuration will be stored in .opensdistro_security index and it will not be read again from yml files. 
So your default will not get impacted. 

If you are migrating from 0.10 to any of ODFE 1.x versions, you can also use validate and migrate APIs for config migration and you don't need to use securityadmin tool.

```
[AAA@ip-xx-yyy-zz-xxx logs]$ curl -k
--cacert ./ca.pem --key ./admin-key.pem --cert ./admin.pem https://localhost/_opendistro/_security/api/validate?pretty
{
"status" : "OK",
"message" : "OK."
}
[AAA@ip-xx-yyy-zz-xxx logs]$ curl -k -XPOST
--cacert ./ca.pem --key ./admin-key.pem --cert ./admin.pem https://localhost/_opendistro/_security/api/migrate?pretty
{
"status" : "OK",
"message" : "Migration completed."
}
```

**Comment by namrataa-p** [comment]
Hi @hardik-k-shah 

I faced similar issues while upgrading and this thread helped me resolve them.
I checked the docs for help at first but there's no info about validate and migrate APIs that are mentioned here.
Please update these APIs in docs as well for others who might come across similar issues.

Thank you.
