### ISSUE TITLE
too match big requests to ldap on rolesmapping

### ISSUE THREAD

**Issue by turbotankist** [opendistro-for-elasticsearch/security#433]
Hello
We are have big domain with 1000+ people.
I made some domain groups with 5-20 persons. 
I've set "resolve_nested_roles: false" 
Now if I try to authenticate opendistro it too long time searching groups in domain ~ 20-30 sec.
if I disable rolesearch - authentication complete in 1s.
I made tcpdump and saw:
opendistro get list of all groups of my username
then it get all users by every group that were searched.
So there some groupes as "alluser", "officeusers" and etc has 1000 users and opendistro downloads  list of them every time. 
~20 MB ldap traffic on 1 signing  on

**Comment by palashhedau** [comment]
Apologies for the delayed response. 
Can you provide tcp dump here so I can analyze and start looking into it.

**Comment by vrozov** [comment]
Please reopen if this is still an issue and provide tcp dump.
