### ISSUE TITLE
Consistant test failures

### ISSUE THREAD

**Issue by lucaswin-amzn** [opendistro-for-elasticsearch/security#434]
# Information

When running the tests via:

`mvn clean test` or `mvn clean package` tests always get stuck on the `WebhookAuditLogTest` test suite.

# Reproduce

`mvn clean test -Dtest=com.amazon.opendistroforelasticsearch.security.auditlog.sink.WebhookAuditLogTest`

**Comment by vrozov** [comment]
CI that includes `mvn test` passes successfully. Please re-open if the issue still reproducible.
