### ISSUE TITLE
Security exception for LDAP users

### ISSUE THREAD

**Issue by mkiran18** [opendistro-for-elasticsearch/security#437]
Hi Team,

Getting 403 security exception on : 
/api/saved_objects/_find?type=index-pattern&fields=title&search=*&search_fields=title&per_page=1
```
error: "Forbidden"
message: "no permissions for [indices:data/read/search] and User [name=ldap_ads_user, roles=[PRC-USER-GROUP], requestedTenant=null]: [security_exception] no permissions for [indices:data/read/search] and User [name=ldap_ads_user, roles=[PRC-USER-GROUP], requestedTenant=null]"
statusCode: 403
```

Role for PRC-USER-GROUP: 
```
{
  "cluster": [],
  "indices": {
    "index1-*": {
      "*": [
        "READ"
      ]
    }
  },
  "tenants": {}
}
```

Role Mapping : 
```
{
  "backendroles": [
    "PRC-USER-GROUP"
  ],
  "hosts": [],
  "users": []
}
```

LDAP login is working fine with the auth info  api call populating backend roles array with the above PRC group.

is there any other additional step missing in mapping the role to appropriate indices ?

EDIT 1:

If i replace the mapping with it works fine.

```
{
      "cluster": [],
      "indices": {
        "*": {
          "*": [
            "READ"
          ]
        }
      },
      "tenants": {}
    }
```
Even the specific Index name also , experiencing the same failure:

```
{
      "cluster": [],
      "indices": {
        "index1-2342": {
          "*": [
            "READ"
          ]
        }
      },
      "tenants": {}
    }
```

**Comment by debjanibnrj** [comment]
Hi @mkiran18,

Thanks for your issue and sorry about the delayed response. 

You mentioned that you had replaced the mapping to 
```
{
      "cluster": [],
      "indices": {
        "*": {
          "*": [
            "READ"
          ]
        }
      },
      "tenants": {}
    }
```

and it started working. Is this still an issue for you currently?

**Comment by mkiran18** [comment]
Hi @debjanibnrj ,
 Issue is similar to the one i reported in other module about a possible bug when the logged-in user has permission on few indices in an indices pattern. More info is here : https://github.com/opendistro-for-elasticsearch/security/issues/142

**Comment by vrozov** [comment]
Duplicate of #142
