### ISSUE TITLE
SSL cert hot reload (PEM files) 

### ISSUE THREAD

**Issue by gplechuck** [opendistro-for-elasticsearch/security#455]
Hey folks,

Have been looking forward to the introduction of SSL cert hot reloading, described here -

https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/release-notes/release-notes-odfe-1.6.0.md
https://github.com/opendistro-for-elasticsearch/security/pull/238

Currently testing v1.6.0 and find that the SSL cert hot reloading feature is not working in my case.

Just checking - has this been tested with SSL certs in Java keystores only, or does it also work for the reloading of SSL certs stored in PEM files?

Running Opendistro v.1.6.0 with correct plugin versions -

```
GET _cat/plugins                                                     
                                   
escdr-test-001 opendistro-job-scheduler        1.6.0.0
escdr-test-001 opendistro-knn                  1.6.0.0
escdr-test-001 opendistro_alerting             1.6.0.0
escdr-test-001 opendistro_index_management     1.6.0.0
escdr-test-001 opendistro_performance_analyzer 1.6.0.0
escdr-test-001 opendistro_security             1.6.0.0
escdr-test-001 opendistro_sql                  1.6.0.0
```

SSL cert for transport and https is currently loaded -

```
    # openssl s_client -connect 127.0.0.1:9200 -showcerts | openssl x509 -noout -text

depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1                                                           
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
Certificate:
    Data:
        Version: 3 (0x2)             
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Apr 29 06:16:43 2020 GMT
            Not After : Jul 28 06:16:43 2020 GMT

```
I replace the SSL cert on disk with an updated version - same issuer, same hostname, only major difference is the expiry date.

When I check the SSL certs API endpoint with a user with ‘admin_all’ privileges, there is no response -
`
GET 127.0.0.1:9200/_opendistro/_security/api/ssl/certs `

When I attempt to reload the certs, there is no response

The SSL cert is not reloaded.

Before I look into this much further - just checking if this feature works with PEM files as well as keystores?

```
PUT 127.0.0.1:9200/_opendistro/_security/api/ssl/transport/reloadcerts 
PUT 127.0.0.1:9200/_opendistro/_security/api/ssl/http/reloadcerts 

```
SSL hot reloads is enabled in elasticsearch.yml -
`
opendistro_security.ssl_cert_reload_enabled: true`

Cheers

**Comment by debjanibnrj** [comment]
Hi @gplechuck,

Thanks for question. This feature should work for both pem and keystore files. 

To enable SSL hot reload you should ensure that the pem files are in the same filepath specified by elasticsearch.yml. 

While making the request to get cert details/reload certificates you need to authenticate the request with the admin cert and key  - 

Eg:
`curl -k -XGET --key admin-key.pem --cert admin.pem https://127.0.0.1:9200/_opendistro/_security/api/ssl/certs`

`curl -k -XPUT --key admin-key.pem --cert admin.pem https://127.0.0.1:9200/_opendistro/_security/api/ssl/http/reloadcerts `

`curl -k -XPUT --key admin-key.pem --cert admin.pem https://127.0.0.1:9200/_opendistro/_security/api/ssl/transport/reloadcerts `

Let me know if this works for you.

**Comment by gplechuck** [comment]
Hi @debjanibnrj ,

Works like a charm, thanks . I was not authenticating the request with the admin cert and key .

Very nice feature, will take the pain out of automating node restarts (safely) when SSL certs are automatically renewed in large cluster.

**Comment by smarshal-Quest** [comment]
Hi. I am also trying to get this to work , testing on v 1.8.0.0, however i get a 401 Unorthorized when  using the admin key and cert.  The same admin certificate any key do work and allow me to update security config  (securityadmin.sh)

**Comment by 2ps** [comment]
Is there a similar command for kibana?

**Comment by Tarasovych** [comment]
@2ps Open Distro for Kibana does not support this feature as far, as I know

**Comment by mhoydis13** [comment]
I feel like I should comment here for someone else who might be struggling with this:   https is required for these api functions, not optional.  You must hit an https-enabled rest port for this to work, otherwise it'll silently fail without any message.  
http:// no good.  
https:// is what you need.    
opendistro_security.ssl.http.enabled: true
