### ISSUE TITLE
Cannot create role using API

### ISSUE THREAD

**Issue by Arbakkinn** [opendistro-for-elasticsearch/security#456]
Hi,

I'm confronted with a very basic and stupid issue, I cannot seem to create roles using the `_security/api/roles/<role>` API path.

I'm following the official documentation with the provided example here : https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#create-role

I put the example role in a file called `role.json` and calling the API using curl as follow:

role.json:
```
{
  "cluster_permissions": [
    "cluster_composite_ops",
    "indices_monitor"
  ],
  "index_permissions": [{
    "index_patterns": [
      "movies*"
    ],
    "dls": "",
    "fls": [],
    "masked_fields": [],
    "allowed_actions": [
      "read"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "human_resources"
    ],
    "allowed_actions": [
      "kibana_all_read"
    ]
  }]
}
```

```
curl -k -H "Content-Type: application/json" -d @role.json -u "user:password" -XPUT https://localhost:9200/_opendistro/_security/api/roles/test_role
```

I'm always getting the same answer:
> {"status":"error","reason":"Could not parse content of request."}

Which is weird because the JSON is valid and I do not have this problem calling other paths of the API like the creation of a user for example.

I think I'm either missing something important or the documentation is maybe incorrect ?

It's worth mentioning that I'm running Elasticsearch on AWS (v6.7), I have no idea which version of Opendistro is behind.

Any help would be greatly appreciated.

**Comment by debjanibnrj** [comment]
Hi @Arbakkinn,

Thanks for your question.

Elasticsearch version 6.7 works with opendistro-security version 0.9 . This version has a different format for the roles API which does not match the documentation. 


The roles request  mentioned in the [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#create-role) is for opendistro-security version 1.0 onwards. I have created  https://github.com/opendistro-for-elasticsearch/security/issues/457 to address this. Sorry for the confusion.

For ES 6.7 you will need to update your roles.json text to the following - 

```
{
      "cluster": [
         "INDICES_MONITOR",
         "CLUSTER_COMPOSITE_OPS"
      ],
      "indices": {
         "movies*": {
            "*": [
               "READ"
            ],
            "_dls_": "",
            "_fls_": null
         }
      },
      "tenants": {
         "human_resources": "RO"
      }
}
```

This should solve your issue with the curl request.

**Comment by Arbakkinn** [comment]
Hi @debjanibnrj 

I tested your JSON role and it worked perfectly so thank you for your answer!

Also thanks for the creation of the issue, because the documentation is indeed misleading on the subject.
