### ISSUE TITLE
Update documentation for roles API (versions 0.9 and 0.10)

### ISSUE THREAD

**Issue by debjanibnrj** [opendistro-for-elasticsearch/security#457]
Roles API input is different for opendistro 0.9 and 0.10. This needs to be updated in the documentation (https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#create-role)

Related Issue: 
https://github.com/opendistro-for-elasticsearch/security/issues/456

**Comment by aetter** [comment]
We recently added old documentation version to the docs, which has the old API: https://opendistro.github.io/for-elasticsearch-docs/docs/other/#old-documentation-versions

We won't host every version, just the final minor version for each major version. In this case, we never tagged a 0.10 version of the docs, so 0.9 is the latest. I suspect we're closing in on the final 1.x version.
