### ISSUE TITLE
Unable to load kibana dashboard from metricsbeat 

### ISSUE THREAD

**Issue by debjanibnrj** [opendistro-for-elasticsearch/security#460]
From opendistro forum issue: 
https://discuss.opendistrocommunity.dev/t/cannot-import-metricbeat-dashboards/2640

I’m using metricbeat and asking myself how to add kibana dashobords.

Using docker.elastic.co/beats/metricbeat-oss:7.4.2
in Kubernetes

Log message is
{
2020-04-22T17:35:07.144Z ERROR instance/beat.go:878 Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /usr/share/metricbeat/kibana: Failed to import dashboard: Failed to load directory /usr/share/metricbeat/kibana/7/dashboard:
error loading /usr/share/metricbeat/kibana/7/dashboard/Metricbeat-aerospike-overview.json: returned 401 to import file: . Response: {“message”:“Session expired”,“redirectTo”:“login”}
error loading /usr/share/metricbeat/kibana/7/dashboard/Metricbeat-apache-overview.json: returned 401 to import file: . Response: {“message”:“Session expired”,“redirectTo”:“login”}
error loading /usr/share/metricbeat/kibana/7/dashboard/Metricbeat-ceph-overview.json: returned 401 to import file: . Response: {“message”:“Session expired”,“redirectTo”:“login”}

**Comment by nugroho-expereo** [comment]
Hi @debjanibnrj I have the same issue. Have you found a solution for it ?

Thank you.
