### ISSUE TITLE
Can opendistro security plugin works with fluentbit?

### ISSUE THREAD

**Issue by jsdevalx** [opendistro-for-elasticsearch/security#467]
Same as title. Can opendistro security plugin works with fluentbit? Could You provide any examlple (TLS/SSL)?

**Comment by vrozov** [comment]
I don't see why it won't work with fluentbit as long as it can support SSL and custom certificates. Configuration on the opendistro for elasticsearch security plugin would be the same for all clients. Please check fluentbit documentation how to configure it for TLS/SSL.

**Comment by DandyDeveloper** [comment]
@vrozov Yes it can. I have this running in production.

**Comment by vrozov** [comment]
@DandyDeveloper Thanks for confirming.

**Comment by cheoalfredo** [comment]
> @vrozov Yes it can. I have this running in production.

can you share how to you got it working ?
