### ISSUE TITLE
Allow user to change their own password.

### ISSUE THREAD

**Issue by hardik-k-shah** [opendistro-for-elasticsearch/security#47]
Currently only Admin or user with REST API access can change password.

So, if there is an user with only read access or write access but does not have an access to REST API can not change a password. 

Irrespective of type of permission user has, he/she must be able to change his own password. 

Thanks @ThibaudF for suggesting [this](https://discuss.opendistrocommunity.dev/t/allow-access-to-users-to-change-their-own-password/599).

**Comment by sujithvm** [comment]
This should be fixed by https://github.com/opendistro-for-elasticsearch/security/pull/200

**Comment by hardik-k-shah** [comment]
this feature was merged under this pull request https://github.com/opendistro-for-elasticsearch/security/pull/200
