### ISSUE TITLE
Incorrect security role in documentation

### ISSUE THREAD

**Issue by SagdeevRR** [opendistro-for-elasticsearch/security#480]
In resource https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/security-roles/ it is writen the "set specify the .opendistro-alerting-alerts index", but in elastic have .opendistro-alerting-alert-history-2020.* indexes. May be need write .opendistro-alerting-alert* index.
Otherwise, an access error occurs and the user does not see the monitor created by him.

**Comment by vrozov** [comment]
@SagdeevRR Please open a new issue for documentation https://github.com/opendistro/for-elasticsearch-docs/issues
