### ISSUE TITLE
Failed to restore backup

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/security#49]
Im having a problem where while im able to install and create s3 backups im not able to restore them.

```
FROM amazon/opendistro-for-elasticsearch:0.9.0
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.6.2.zip
RUN bin/elasticsearch-keystore add --force --stdin s3.client.default.access_key <<< "XXXX"
RUN bin/elasticsearch-keystore add --force --stdin s3.client.default.secret_key <<< "XXXX"
```

When trying to restore a backup i get:
```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]"
  },
  "status": 403
}
```

The same error i get when using the snapshotrestore user.
Could you help me with this?

**Comment by aetter** [comment]
Hi @mporracindie and @hksk, sorry you ran into this issue. I have a PR for the documentation that I hope will address it: https://github.com/opendistro/for-elasticsearch-docs/pull/74/files#diff-f0d0cd8cf835cf4b3c7a1eb48974d761

In short, try excluding global state and the `.opendistro_security` index on restore:

```json
POST _snapshot/my-repository/your-snapshot/_restore
{
  "indices": "-.opendistro_security",
  "include_global_state": false
}
```

Let me know if it works out for you. Thanks!

**Comment by hksk** [comment]
I confirm the @aetter  suggestion, works :) thanks men.

**Comment by mporracindie** [comment]
I ll be doing some test later. 
Thanks @aetter !

**Comment by tantra35** [comment]
@aetter This doesn't work due we got another error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "Unexpected exception cluster:admin/snapshot/restore"
      }
    ],
    "type" : "security_exception",
    "reason" : "Unexpected exception cluster:admin/snapshot/restore"
  },
  "status" : 500
}
```

We had many hopes on opendistro but at now days it's a "chain of quest", where many features doesn't works as expected, with very bad quality of code itself(early alpha???)

**Comment by bollohz** [comment]
With OpenDistro version 0.10 I've same problem. In any case with admin user is impossible to call the `_restore` endpoint. 
Is there some workaround to solve the issue?

**Comment by aashishmodak** [comment]
It worked for me with below payload
`payload = {
   "indices": "-.kibana*,-.opendistro*",
   "include_global_state": False
 }`
Basically replace the `opendistro-security` with `opendistro*`

**Comment by definesfineout** [comment]
> It worked for me with below payload
> `payload = { "indices": "-.kibana*,-.opendistro*", "include_global_state": False }`
> Basically replace the `opendistro-security` with `opendistro*`

Worked for me as well. I was following [AWS docs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html#es-managedomains-snapshot-client-python) but changing to `opendistro*` did it.
