### ISSUE TITLE
DLS performance issue while terms in huge array

### ISSUE THREAD

**Issue by timothynode** [opendistro-for-elasticsearch/security#497]
We were using dls to build user custom privilege system in kibana.
We have met performance issue while using huge terms in filter, such as:
`{ "terms" : {
            "appId" : [
	            "00004c9a2a3408fa108637b5e56dde4a284f53bf",
				"0008f1f3231fa94dd870e219e574add6c3c5cee8",
				"00206dd6368c87c08bd4631ef1340ec45aace6bf",
				"00231d66b0aa0a9dbe98ce11ec2f2b27e367a2fb",
				"002aa1e6b1d2873d7f2e692876e8c9be77acd950",
				"003266a319036da6d86baaf4e72f3f779cef113a",
				"0034aede41afb566cb3f7c235be8106e62b2fed8",
				"003df3f126bf7ecba1f86c81cd1490c92d1dc18a",
				"0041345214cc64e149ea527befce4caac60ba8fb",
				...over 1000 appIds...
		]
	}
}`

Then simple queries like "appId:002aa1e6b1d2873d7f2e692876e8c9be77acd950" becomes pretty slow. it tooks over 6secs, in the mean time, the super admin account only took 300ms.

![image](https://user-images.githubusercontent.com/1754054/84098000-a87ee380-aa38-11ea-84e6-c09ccf1b33bc.png)

looks like, the plugin is trying to fetch huge result instead of just append the query then send it to es.

it's there any help i can fix it, or any doc i can find to help me understand how it works ( https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/document-level-security/ this doc is too simple )

**Comment by vrozov** [comment]
What is the performance of the DLS term query if it is executed by the admin? The DLS by itself should not impact performance much, it all depends on the complexity of the query used to define DLS.

**Comment by timothynode** [comment]
took 1.5s using admin account.
repeat over 5 times.

**Comment by vrozov** [comment]
try the following query:
```
{
  "query": {
    "bool": {
      "minimum_should_match": 1, 
      "should": [
        {
          "constant_score": {
            "filter": {
              "terms" : { "appId" : [ "00004c9a2a3408fa108637b5e56dde4a284f53bf", "0008f1f3231fa94dd870e219e574add6c3c5cee8", ...] }
            },
            "boost": 1.0
          }
        }
      ],
      "must": [
        {
          "term": {
            "appId": "002aa1e6b1d2873d7f2e692876e8c9be77acd950"
          }
        }
      ]
    }
  }
}
```
it quite closely matches what DLS will execute.

**Comment by timothynode** [comment]
> try the following query:
> 
> ```
> {
>   "query": {
>     "bool": {
>       "minimum_should_match": 1, 
>       "should": [
>         {
>           "constant_score": {
>             "filter": {
>               "terms" : { "appId" : [ "00004c9a2a3408fa108637b5e56dde4a284f53bf", "0008f1f3231fa94dd870e219e574add6c3c5cee8", ...] }
>             },
>             "boost": 1.0
>           }
>         }
>       ],
>       "must": [
>         {
>           "term": {
>             "appId": "002aa1e6b1d2873d7f2e692876e8c9be77acd950"
>           }
>         }
>       ]
>     }
>   }
> }
> ```
> 
> it quite closely matches what DLS will execute.

it takes same time as normal user query

**Comment by vrozov** [comment]
Try to optimize your DLS query definition.
