### ISSUE TITLE
How to update(rotate) certificates on an opendistro Elasticsearch cluster?

### ISSUE THREAD

**Issue by namrataa-p** [opendistro-for-elasticsearch/security#500]
Hi,

I'm using open-distro-elasticsearch v6.7.1 and security plugin v0.9.0. 
I have gone through the certificate setup steps mentioned in the documentation and was wondering if there's any flow defined to update the certificates across the cluster with little to no downtime while keeping the data on the cluster safe. 
Currently, I'm following [Elasticsearch rolling upgrade](https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/rolling/) steps for certificate update but it would be nice to have a recommended approach to do this.

**Comment by debjanibnrj** [comment]
Hi @namrataa-p ,

Thanks for your interest in improving our community. This feature is available in the latest versions of ODFE security for version 0.9 onwards.

For more details you can refer to - https://github.com/opendistro-for-elasticsearch/security/pull/238

**Comment by namrataa-p** [comment]
Hi @debjanibnrj ,

Thanks for the response!

I read the API details mentioned in #238 and there's this line that says, 'This API is very sensitive so currently it only allows users to replace their expired certificates with valid certificates issued with the **same Issuer**/Subject DN and SAN.'. In my case, I'm replacing the CA certificate too, so according to this line I can't use this API to update certificates, right?

Is this API added to the documentation yet? I couldn't find it there.

**Comment by debjanibnrj** [comment]
Hi @namrataa-p, 
Yes, unfortunately the API does not allow replacing the CA certificate, only the transport and http certificates. 

Created https://github.com/opendistro-for-elasticsearch/security/issues/504 to ensure its updated in the documentation.

**Comment by namrataa-p** [comment]
Hi @debjanibnrj ,

Thanks for the response and solution.
