### ISSUE TITLE
Not able to change Read-only block for .opendistro_security index

### ISSUE THREAD

**Issue by firoshaq** [opendistro-for-elasticsearch/security#508]
I was not able to create new roles,users etc from kibana and was getting an Internal server error. Further checking I see the below errors in log.

```
"message":"Error index [.opendistro_security] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];: Internal Server Error"}
``` 

I see one solution as mentioned [here](https://github.com/opendistro-for-elasticsearch/security/issues/107) , but it is not working for me and I get an unauthorized error

```
curl -k --cert ./admin --key ./admin-key.pem -X PUT -H "Content-Type: application/json" -d '{"index.blocks.read_only_allow_delete": null }' http://localhost:9200/.opendistro_security/_settings
Unauthorized
```

Could someone shed some light on this issue?

**Comment by vrozov** [comment]
Please check that `./admin` is a valid certificate. Check results of `curl -k --cert ./admin --key ./admin-key.pem https://localhost:9200/`

**Comment by firoshaq** [comment]
I get an unauthorized error while running curl -k --cert ./admin --key ./admin-key.pem https://localhost:9200/

And I also checked the validity of the certificates using below and it says it is valid for 10 years.
 
openssl x509 -enddate -subject -noout -in /etc/elasticsearch/admin.pem

**Comment by vrozov** [comment]
Check that the subject of the "admin.pem" certificate matches "opendistro_security.authcz.admin_dn" settings.

**Comment by firoshaq** [comment]
I have run openssl x509 -enddate -subject -noout -in /etc/elasticsearch/admin.pem

with below output

subject= /C=DE/L=xxx/O=xxx/OU=xxx/CN=logging

and checked the "opendistro_security.authcz.admin_dn" settings in /etc/elasticsearch/elasticsearch.yml

and the output is below

- "CN=logging,OU=xxx,O=xxxy,L=xxx,C=DE"

Both the contents are similar.


Just one point to add here that we are facing this issue for a clustered elk.

**Comment by vrozov** [comment]
The subject in the certificate must match exactly one of the admin dn in elasticsearch.yml and all ES nodes must have the same admin_dn settings. To troubleshoot the issue further, enable TRACE level settings for `com.amazon.opendistroforelasticsearch.security.configuration.AdminDNs`
