### ISSUE TITLE
Bug of index security?

### ISSUE THREAD

**Issue by HagunKim** [opendistro-for-elasticsearch/security#533]
Environments: Opendistro ES 1.8.0 and Kibana 1.8.0.

Symptom:
I have several indices containing myindex-*.

I set MY_ROLE like this.
Cluster permission: nothing
Index permission: myindex-* (indices_all)
And then map MY_ROLE with test-user.

After login with test-user, I tried 'GET /_search/' in Kibana Dev Tools.
It returns like this:

{
　"error" : {
　　"root_cause" : [
　　　{
　　　　"type" : "security_exception",
　　　　"reason" : "no permissions for [indices:data/read/search] and User [name=test-user, backend_roles=[], requestedTenant=__user__]"
　　　}
　　],
　　"type" : "security_exception",
　　"reason" : "no permissions for [indices:data/read/search] and User [name=test-user, backend_roles=[], requestedTenant=__user__]"
　},
　"status" : 403
}

Expected result: indices information for myindex-*

In x-pack security, I can see expected result.
It was also without cluster permission and with myindex-*(all).

Actually, I want to get only a list of indices that I have access permission.
Is this bug or something wrong with my settings?

**Comment by vrozov** [comment]
It is expected behavior. Please see discussion in #142.
