### ISSUE TITLE
Creating multiple users and roles concurrently fails with version conflict error

### ISSUE THREAD

**Issue by devishankarjha** [opendistro-for-elasticsearch/security#538]
We are using OpedDistro version 0.10.0 with ES 6.8.1. 
Our ES cluster has 3 data/master nodes. We are creating 100 users with roles and rolesmapping concurrently. 
Lot of create user/roles/roles/mapping request fails with version conflict error.
Below are some of the ES responses:

{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][rolesmapping]: version conflict, current version [35] is different than the one provided [34]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][internalusers]: version conflict, current version [47] is different than the one provided [46]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][internalusers]: version conflict, current version [47] is different than the one provided [46]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][roles]: version conflict, current version [35] is different than the one provided [34]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][internalusers]: version conflict, current version [44] is different than the one provided [43]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][rolesmapping]: version conflict, current version [42] is different than the one provided [41]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][roles]: version conflict, current version [45] is different than the one provided [44]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][internalusers]: version conflict, current version [49] is different than the one provided [48]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][rolesmapping]: version conflict, current version [44] is different than the one provided [43]"}
{"status":"INTERNAL_SERVER_ERROR","message":"Error [security][roles]: version conflict, current version [48] is different than the one provided [47]"}

**Comment by debjanibnrj** [comment]
Hi @devishankarjha this error is thrown by elasticsearch to prevent data loss. Please try re-fetching the doc and try to update again with the latest updated version.

**Comment by cliu123** [comment]
> Hi @devishankarjha this error is thrown by elasticsearch to prevent data loss. Please try re-fetching the doc and try to update again with the latest updated version.

@devishankarjha Has the issue been resolved? Please feel free to reopen it if not.
