### ISSUE TITLE
Snapshot restore is not working due to security permission

### ISSUE THREAD

**Issue by TWpower** [opendistro-for-elasticsearch/security#553]
Hello?

I just made snapshot which name is ```metricbeat-7.7.0-2020.07.09-restore-2020.07.10_02:11:26``` on ```test-user``` repository.
Next, I tried to restore from that snapshot.

That snapshot has only one index``` metricbeat-7.7.0-2020.07.09-restore``` and I'd like to rename it as ```metricbeat-7.7.0-2020.07.09-restore-restore```.

However I tried it but it fails and returns error like below.

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [] and User [name=test-user, backend_roles=[], requestedTenant=__user__]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [] and User [name=test-user, backend_roles=[], requestedTenant=__user__]"
  },
  "status" : 403
}
```

This is command that is use.

```
POST /_snapshot/test-user/metricbeat-7.7.0-2020.07.09-restore-2020.07.10_02:11:26/_restore
{
  "indices": "metricbeat-7.7.0-2020.07.09-restore",
  "ignore_unavailable": true,
  "include_global_state": false,              
  "rename_pattern": "metricbeat-7.7.0-2020.07.09-restore",
  "rename_replacement": "metricbeat-7.7.0-2020.07.09-restore-restore",
  "include_aliases": false
}
```

I both tried on ```test-user``` and ```admin``` user.

Is there anything wrong in my command?

**Comment by debjanibnrj** [comment]
Thanks for your question @TWpower. Could you mention which ES version you're using?

**Comment by TWpower** [comment]
Hello @debjanibnrj 
Its version is 1.8.0

**Comment by sunnybatabyal** [comment]
Hi Team, @debjanibnrj ,
Facing the same. Do we have any update on this?

**Comment by debjanibnrj** [comment]
Ensure that you have the following settings enabled - 

https://github.com/opendistro-for-elasticsearch/security/blob/d420f16ed1e37244e1d437d5f73740237c5ded8f/securityconfig/elasticsearch.yml.example#L191-L201

**Comment by sunnybatabyal** [comment]
Hi,
We are using OD `0.10.0` as we are on ES `6.8.1`
After adding the following configurations in `elasticsearch.yml`
`opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: false`
still we are getting `403`.

Also, we have tried with the admin certificate still facing the same `403` error.
`curl -k -XPOST https://localhost:9200/_snapshot/182d30ddbc6a4e6dbc7f8d33e8676c28/202009301100/_restore?wait_for_completion=true -u elastic:DLfWez5JCK --insecure --cert admin.pem --key admin-key.pem  -H 'Content-Type: application/json' -d' {"indices": "oscs_configuration","ignore_unavailable": true,"include_global_state": false}'`

Is there anything we are missing? Can you please help?

**Comment by debjanibnrj** [comment]
Hi @ sunnybatabyal, Were you able to resolve the issue?

**Comment by debjanibnrj** [comment]
closing issue, feel free to reopen if problem persists.
