### ISSUE TITLE
Open Distro Security Roles setting not working in ODFE 1.9

### ISSUE THREAD

**Issue by shawnz** [opendistro-for-elasticsearch/security#555]
Hi there, previously we had our ODFE internal_users configuration set up like follows:

```yaml
---
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "..."
  reserved: true
  hidden: false
  backend_roles: []
  attributes: {}
  description: "Admin user"
  opendistro_security_roles:
  - "all_access"
  static: false
logstash:
  hash: "..."
  reserved: false
  hidden: false
  backend_roles: []
  attributes: {}
  description: "Logstash user"
  opendistro_security_roles:
  - "logstash"
  static: false
kibanaserver:
  hash: "..."
  reserved: true
  hidden: false
  backend_roles: []
  attributes: {}
  description: "Kibanaserver user"
  opendistro_security_roles:
  - "kibana_server"
  static: false
filebeat:
  hash: "..."
  reserved: false
  hidden: false
  backend_roles: []
  attributes: {}
  opendistro_security_roles:
  - "filebeat"
  static: false
```

This worked fine until upgrading to ODFE 1.9 after which point kibana and logstash no longer had any permissions. I would receive errors such as the following in the elasticsearch log file:

```
[2020-07-11T19:27:10,879][INFO ][c.a.o.s.p.PrivilegesEvaluator] [node-1] No cluster-level perm match for User [name=kibanaserver, backend_roles=[], requestedTenant=null] Resolved [aliases=[*], allIndices=[*], types=[*], originalRequested=[*], remoteIndices=[]] [Action [cluster:monitor/nodes/info]] [RolesChecked []]
[2020-07-11T19:27:10,880][INFO ][c.a.o.s.p.PrivilegesEvaluator] [node-1] No permissions for [cluster:monitor/nodes/info]
[2020-07-11T19:27:13,112][INFO ][c.a.o.s.p.PrivilegesEvaluator] [node-1] No cluster-level perm match for User [name=logstash, backend_roles=[], requestedTenant=null] Resolved [aliases=[*], allIndices=[*], types=[*], originalRequested=[*], remoteIndices=[]] [Action [cluster:monitor/main]] [RolesChecked []]
[2020-07-11T19:27:13,112][INFO ][c.a.o.s.p.PrivilegesEvaluator] [node-1] No permissions for [cluster:monitor/main]
```

Applying the security roles using roles_mapping instead fixes the issue.

Also, after applying the workaround, if I try to use the Security page in Kibana to add the roles back to the internal users, it just logs me out upon clicking "submit" and doesn't apply the change.

I am wondering if this might be related to change #486 .

**Comment by debjanibnrj** [comment]
Hi @shawnz,

Thanks for bringing this issue to our attention. I have submitted a fix for this issue(https://github.com/opendistro-for-elasticsearch/security/pull/556).

**Comment by shawnz** [comment]
Thank you very much for looking into this and for the fast turnaround time on the fix. I appreciate your hard work on this project.

**Comment by debjanibnrj** [comment]
Fix https://github.com/opendistro-for-elasticsearch/security/pull/556 Is now submitted. Let me know if it solves your issue.  Thanks!

**Comment by tmanninger** [comment]
I have the same issue.
How can i test this bugfix? Is there a builded elasticsearch plugin with this fix available?

**Comment by debjanibnrj** [comment]
Hi @tmanniger, The fix is deployed for opendistro-1.8 and master branches. Could you provide the ES version that you're testing with?

**Comment by tmanninger** [comment]
Hi @debjanibnrj, i am using opendistro-1.9. Can you deploy this fix for 1.9?

**Comment by debjanibnrj** [comment]
Hi @tmanniger, The fix has been deployed on the master branch https://github.com/opendistro-for-elasticsearch/security/commit/4a6ed34b8788260403fe09ccd40c0d96136428d2. We're in the process of cutting a new tag and building the fix in opendistro-for-elasticsearch:1.9. Will update once the build has been made.

**Comment by debjanibnrj** [comment]
Fix for this issue is available in the following release - https://github.com/opendistro-for-elasticsearch/security/releases/tag/v1.9.0.1

**Comment by tmanninger** [comment]
Hi @debjanibnrj , thanks it's working now!

**Comment by tmanninger** [comment]
Hi, is there a similar issue with the static action groups?

my logstash user have the following roles settings:
```user_logstash:
  cluster_permissions:
  - cluster_composite_ops
  - ODS_CLUSTER_READ_ILM
  index_permissions:
  - index_patterns:
    - accesslog*
    - authlog*
    - dns*
    - mail*
    - mysql*
    - netmgmt*
    - syslog*
    - cloudflare*
    allowed_actions:
    - crud
    - create_index
    - indices:admin/get
    - manage_aliases
```

After upgrading opendistro from 1.6.0 to 1.9.0.1, i get the following error:
```
curl -u logstash:xxxxx https://localhost:9200/_ilm/policy                                                                                                
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [cluster:admin/ilm/get] and User [name=logstash, backend_roles=[], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [cluster:admin/ilm/get] and User [name=logstash, backend_roles=[], requestedTenant=null]"},"status":403}%
```

after adding the permission "cluster:admin/ilm/get" to the cluster permissions of this role, the request works without a permission error.
But the role already contains the static action group "ODS_CLUSTER_READ_ILM", which contains "cluster:admin/ilm/get":
https://github.com/opendistro-for-elasticsearch/security/blob/cbcc6245bd923c545fc7e52dabe1bed267ddbf6c/src/main/resources/static_config/static_action_groups.yml

Why is this not working with the action group "ODS_CLUSTER_READ_ILM" in cluster settings?

With 1.6.0.0, everything works fine.

**Comment by shawnz** [comment]
After installing the linked update, I can't use SAML auth. Reverting to 1.9.0.0 fixes the issue. Maybe it has something to do with #603. I will post a new issue with the error message.

**Comment by juliennix** [comment]
When can we expect it to be added in new docker image ?
Kr
