### ISSUE TITLE
problem with user permission 

### ISSUE THREAD

**Issue by sidhommoez** [opendistro-for-elasticsearch/security#557]
Hello,

i have a problem with roles i created a new user and role and i mapped the user to the role
the user can access to one index
im trying to liste the indexes with /\_cat/indices?v i get this error:

{
"error": {
"root_cause": [
{
"type": "security_exception",
"reason": "no permissions for [indices:monitor/settings/get] and User [name=Moez, backend_roles=[_SUPERADMIN], requestedTenant=null]"
}
],
"type": "security_exception",
"reason": "no permissions for [indices:monitor/settings/get] and User [name=Moez, backend_roles=[_SUPERADMIN], requestedTenant=null]"
},
"status": 403
}

the permission [indices:monitor/settings/get] is configured but without any solution for this

but if i try to get one index with /\_cat/myindex it works
and im getting permissions errors inside kibana (the same error above)

**Comment by vrozov** [comment]
Please check `do_not_fail_on_forbidden` settings.

**Comment by vrozov** [comment]
Please re-open if it is still an issue.
