### ISSUE TITLE
About index name pattern used inside Kibana 

### ISSUE THREAD

**Issue by 8wlgns** [opendistro-for-elasticsearch/security#574]
Hello. I have a question about the index name used inside Kibana like .kibana

Currently my elasticsearch index has no exact same name as .kibana 
(The official document says all objects are saved at .kibana
https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#manage-kibana-indices)

But for admin user, it seems to use .kibana_1 index.
(When I using search api for getting index-pattern created by admin, Theses are only finded at .kibana_1 index.)
 
And I created "test-user" also, the user seems to use .kibana_hashnumber_username_1 and
.kibana_hashnumber_username_2 index.

So I have two questions. 

1. Is it correct to use .kibana_1 instead of .kibana for admin user? 
2. What is the numbers _1, _2 meaning after the index name?

**Comment by vrozov** [comment]
Please see [Kibana docs](https://www.elastic.co/guide/en/kibana/current/upgrade-migrations.html) that explains how Kibana persists and migrates its objects.
