### ISSUE TITLE
Backup security configurations

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/security#58]
As discussed on #49 backing up and restoring data from s3 its been tested and worked just fine but this leaves out all the security configurations. 
Is it possible to backup and restore this?

**Comment by aetter** [comment]
Hi @mporracindie, yeah, you can dump your settings out to YML files using: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/security-admin/#backup-and-restore

Let me know if that does the trick!
