### ISSUE TITLE
empty .opendistro_security index and fluentbit hash passwd question

### ISSUE THREAD

**Issue by jsdevalx** [opendistro-for-elasticsearch/security#581]
2 Issues/Questions
1.
I have security initialized. There are plenty of users in kibana Security tab but when I am looking into .opendistro_security index. There are no documents -> _count=0
https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/
Provide a username and password. The security plugin automatically hashes the password and stores it in the .opendistro_security index.

2.
I would like to get hash for some user. I would like to use it in fluentbit output plugin in HTTP_Passwd instead of plain text password. Do You know if it works (will be compatible)?

**Comment by cliu123** [comment]
Please try `/.opendistro_security/_doc/internalusers`. It gives the encoded string of internal user. After decoding it, it will show the username, password and hash.
