### ISSUE TITLE
Support for Elasticsearch 7

### ISSUE THREAD

**Issue by havidarou** [opendistro-for-elasticsearch/security#60]
Hello all,
Just wondering, are you working on adapting opendistro for Elasticsearch 7?

If that is so (which I hope), do you have an ETA?
Regards.

**Comment by aetter** [comment]
Hi @havidarou, we support 7.0.1 now: https://aws.amazon.com/blogs/opensource/open-distro-for-elasticsearch-version-1-0-0-available/
