### ISSUE TITLE
Opendistro elastic not able to work with kafka-connect-elasticsearch

### ISSUE THREAD

**Issue by agujrathi** [opendistro-for-elasticsearch/security#613]
Hi team,

Looks like the default configuration of opendistro not able to work with kafka-connect-elasticsearch connector.
It fails at...

`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException`

By default the connector uses SSL certificates..
below is the configuration from kafka-connect-elasticsearch-connector

```
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test-elasticsearch-sink
key.ignore=true
connection.url=https://localhost:9200
type.name=kafka-connect

elastic.security.protocol=SSL
elastic.https.ssl.keystore.location=/home/directory/elasticsearch/config/certs/keystore.jks
elastic.https.ssl.keystore.password=asdfasdf
elastic.https.ssl.key.password=asdfasdf
elastic.https.ssl.keystore.type=JKS
elastic.https.ssl.truststore.location=/home/directory/elasticsearch/config/certs/truststore.jks
elastic.https.ssl.truststore.password=asdfasdf
elastic.https.ssl.truststore.type=JKS
elastic.https.ssl.protocol=TLS
```

It asks for keys strictly and not finding which keys to be provided to get connected with elasticsearch.
opendistro elastic fails with error:

`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException`

Strange that there was not a single mention of this anywhere gooleing... :(

Please let me know if this is an issue .. If not, please help on this the same to point to correct path and way to connect with..

This link says about re-generating keys.. but not sure how it would affect the existing work flow..
https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/security.html

Please advice if I can use same keys as in config folder.. generated with demo certificate.. and which keys to be used... in above config..

**Comment by vrozov** [comment]
Please make sure that you can query elasticsearch using `curl` first.

**Comment by agujrathi** [comment]
You are right.. Not able to connect via curl too..

curl: (77) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Not sure which certificates to be used from opendistro and how.. I have used the install-demo-certificates script in opendistro elasticsearch plugin.
Please advice to get smooth connection with kafka-connect-elasticsearch..

**Comment by debjanibnrj** [comment]
It appears that you're using a self-signed cert. By default curl doesn't know that it can trust that the server is who it says it is, and doesn't want to talk.

You can attempt to do the following - 
* import the cert into your trust store (best and most secure)
* apply the -k or --insecure switch to ignore and continue. This may be fine for local development.
* use a real cert, signed by a trusted CA

**Comment by agujrathi** [comment]
Able to connect via curl -k option..
However,
As logstash & kibana can disable ssl verification check... so same way, which param is controlled the disable ssl verification in kafka-connect-elasticsearch ?  I dont want to verifiy and validate certs..

**Comment by vrozov** [comment]
> As logstash & kibana can disable ssl verification check... so same way, which param is controlled the disable ssl verification in kafka-connect-elasticsearch ? I dont want to verifiy and validate certs..

Please route your question to kafka-connect-elasticsearch
