### ISSUE TITLE
Index mask for ldap group

### ISSUE THREAD

**Issue by e11it** [opendistro-for-elasticsearch/security#66]
Hi!

It's possible to define index mask as `${user_name}-*` when creating role.

I want to have single role/role mapping for a number of ldap groups.
Is it possible to create mask for group?

**Comment by cliu123** [comment]
Please check the [doc for field masking](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/field-masking/).
Please feel free to reopen the issue if it doesn't help.
