### ISSUE TITLE
Enable index access to super admin only.

### ISSUE THREAD

**Issue by skkosuri-amzn** [opendistro-for-elasticsearch/security#666]
Provide mechanisms to declare an index as "system" index. System index is an index only super-admin can access. No role would enable access to the system indices.

Use case: System indices could be used to store configurations by plugins. 

Specify a list of indices to mark as system. 
`opendistro_security.system_indices.enabled: true`
`opendistro_security.system_indices.indices: [.opendistro-alerting-config]`

**Comment by anirudha** [comment]
can this issue be closed ?
