### ISSUE TITLE
Make release notes follow the unified formats

### ISSUE THREAD

**Issue by peterzhuamazon** [opendistro-for-elasticsearch/security#672]
Hello, we have noticed that several release notes including the recent 1.10.0.0 one are not matching the naming convention or formats described in the unified format docs.

Please make sure to follow this naming convention:
“opendistro-for-elasticsearch-\<plugin repo name>.release-notes-<4 digit plugin version number>.md”

Thank you very much.

**Comment by camerski** [comment]
Fixed with https://github.com/opendistro-for-elasticsearch/security/pull/708 and https://github.com/opendistro-for-elasticsearch/security/pull/707
