### ISSUE TITLE
No permission for update _all/_setting

### ISSUE THREAD

**Issue by Mudboyzh** [opendistro-for-elasticsearch/security#684]
Hi, I tried to update `"index.unassigned.node_left.delayed_timeout"` from kibana dev tools, like this
```
PUT _all/_settings
{
  "settings": {
    "index.unassigned.node_left.delayed_timeout": "3m"
  }
}
```
but i got 
```{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
  },
  "status" : 403
}
```

I found https://github.com/opendistro-for-elasticsearch/security/issues/107 that using admin certificate,
So I call api with  admin certificate.  Here is my curl
```
curl -X PUT "localhost:9200/_all/_settings?pretty" -H 'Content-Type: application/json' -u admin --cert admin.pem --key admin-key.pem --insecure -d'
{
  "settings": {
    "index.unassigned.node_left.delayed_timeout": "3m"
  }
}
'
```
but I got the same response(403) .

Log in elasticsearch
```
[c.a.o.s.p.OpenDistroSecurityIndexAccessEvaluator] [es-node-1] indices:admin/settings/update for '_all' indices is not allowed for a regular user
```
The `admin.pem` and `admin-key.pem` can be used to update opendistro_security setting with `securityadmin.sh`

Did I miss something?

**Comment by KillObama** [comment]
yes, It is

**Comment by Mudboyzh** [comment]
Hi @KillObama , I don't get it. What do you mean?

**Comment by debu99** [comment]
any update?

**Comment by cliu123** [comment]
Given that you were using admin certificate, why were you add `--insecure`?

**Comment by Mudboyzh** [comment]
Hi @cliu123, because the certificates are self-signed.  
Without `--insecure`, `curl` would get error about CA verification

**Comment by cliu123** [comment]
Please see [this doc](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/cross-cluster-search/#walkthrough
) 
Proper roles are needed to update '_all' indices.
