### ISSUE TITLE
Kibana multi-tenancy dashboards

### ISSUE THREAD

**Issue by bogdankatishev** [opendistro-for-elasticsearch/security#69]
Hi

I am trying to load different (auditbeat) dashboards in a specific tenant (admin_tenant).
I am using the config attribute: `setup.dashboards.kibana_index` in `auditbeat.yml`. This comes from the official documentation of auditbeat itself.

So the result is: `setup.dashboards.kibana_index: ".kibana_<hash>_admintenant"` like specified in the opendistro documentation about multi-tenancy.

But somehow, after restarting auditbeat and applying the changes, auditbeat says that the kibana dashboards are loaded succesfully, but ONLY in the private_tenant.

I was thinking of maybe there is a solution or workaround for this? Or am I doing something wrong?

**Comment by attachmentgenie** [comment]
+1

**Comment by rlk5546** [comment]
I would call this a workaround:  

1. From the private tenant, Management > Saved Objects > Export
2. Export all the associated dashboards, visualizations, and saved searches.
3. Switch to desired Tenant
4. Import all associated dashboards, visualizations, and saved searches.

If you've forgotten something, you'll know rather quickly. Just go back and export the missing parts from the private tenant and import them into where you want them.

rlk

**Comment by Artur98md** [comment]
> I would call this a workaround:
> 
> 1. From the private tenant, Management > Saved Objects > Export
> 2. Export all the associated dashboards, visualizations, and saved searches.
> 3. Switch to desired Tenant
> 4. Import all associated dashboards, visualizations, and saved searches.
> 
> If you've forgotten something, you'll know rather quickly. Just go back and export the missing parts from the private tenant and import them into where you want them.
> 
> rlk

It will not work because exported objects will be added to kibana default index and not to the desired tenant or will be added to all tenants at once.

**Comment by rlk5546** [comment]
> > I would call this a workaround:
> > 
> > 1. From the private tenant, Management > Saved Objects > Export
> > 2. Export all the associated dashboards, visualizations, and saved searches.
> > 3. Switch to desired Tenant
> > 4. Import all associated dashboards, visualizations, and saved searches.
> > 
> > If you've forgotten something, you'll know rather quickly. Just go back and export the missing parts from the private tenant and import them into where you want them.
> > rlk
> 
> It will not work because exported objects will be added to kibana default index and not to the desired tenant or will be added to all tenants at once.

Actually it does.  I use this method all the time..  I develop dashboards, visualizations, and saved searches in my private tenant and use this method to move them to another after they are completed.  I can also import the default dashboards, visualizations, and saved searches for various beats, make some edits and export/import them to the desired tenant.  This helps keep the unwanted, unneeded, or non-working dashboard items out of production.  I care not which kibana index they are imported to, but they do not show up in any other tenant. They only show in the intended tenant after import.

rlk

**Comment by Artur98md** [comment]
> > > I would call this a workaround:
> > > 
> > > 1. From the private tenant, Management > Saved Objects > Export
> > > 2. Export all the associated dashboards, visualizations, and saved searches.
> > > 3. Switch to desired Tenant
> > > 4. Import all associated dashboards, visualizations, and saved searches.
> > > 
> > > If you've forgotten something, you'll know rather quickly. Just go back and export the missing parts from the private tenant and import them into where you want them.
> > > rlk
> > 
> > 
> > It will not work because exported objects will be added to kibana default index and not to the desired tenant or will be added to all tenants at once.
> 
> Actually it does. I use this method all the time.. I develop dashboards, visualizations, and saved searches in my private tenant and use this method to move them to another after they are completed. I can also import the default dashboards, visualizations, and saved searches for various beats, make some edits and export/import them to the desired tenant. This helps keep the unwanted, unneeded, or non-working dashboard items out of production. I care not which kibana index they are imported to, but they do not show up in any other tenant. They only show in the intended tenant after import.
> 
> rlk

Did you use kibana API or you made all changes via UI?
Could you please post your es and kibana configs?

**Comment by masayyed** [comment]
> 
> 
> I would call this a workaround:
> 
>     1. From the private tenant, Management > Saved Objects > Export
> 
>     2. Export all the associated dashboards, visualizations, and saved searches.
> 
>     3. Switch to desired Tenant
> 
>     4. Import all associated dashboards, visualizations, and saved searches.
> 
> 
> If you've forgotten something, you'll know rather quickly. Just go back and export the missing parts from the private tenant and import them into where you want them.
> 
> rlk

This is working absolutely fine.

**Comment by cliu123** [comment]
Please reopen the issue if the workarounds provided don't help.
