### ISSUE TITLE
Role Group mapping is case sensitive.

### ISSUE THREAD

**Issue by avanand-git** [opendistro-for-elasticsearch/security#709]
Hi There,
How to make the LDAP role_mapping case in-sensitive.

- My roles_mapping.yml has 
admin:
   readonly: true
   backendroles:
     - "cn=PDS-KIBANA-ELASTICSEARCH-ADMIN,ou=Groups,dc=hcs,dc=com"

Example:
- I have group in LDAP
 "cn=PDS-KIBANA-ELASTICSEARCH-ADMIN,ou=Groups,dc=hcs,dc=com"

When a user is member of this group, Query returns

memberOf: cn=pds-kibana-elasticsearch-admin,ou=groups,dc=hcs,dc=com

In this case kibana is not finding the mapping and giving permission error.  Just GROUP name is coming up as lowercase causes it to fail.

Thanks in advance.
Anand.

**Comment by cliu123** [comment]
Role Group Mapping is case sensitive by design. Mappings with different capitalization are treated as different mappings.
