### ISSUE TITLE
Failed to start elasticsearh. Can`t create security index.

### ISSUE THREAD

**Issue by Pupkur** [opendistro-for-elasticsearch/security#73]
```
.opendistro_security index does not exists, attempt to create it ... ERR: An unexpected IllegalArgumentException occured: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [2670]/[1000] maximum shards open;
Trace:
java.lang.IllegalArgumentException: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [2670]/[1000] maximum shards open;
```

And when I`m trying:
```
curl -k -X PUT https://SERVER_IP:9200/_cluster/settings -H "Content-Type: application/json" -d '{ "persistent": { "cluster.max_shards_per_node": "3000" } }'
```
Got error:
`
Open Distro Security not initialized.
`

**Comment by aetter** [comment]
Hi @Pupkur, try adding the setting to `elasticsearch.yml` so that you can get the cluster up and running. Then you can adjust as necessary.

**Comment by Pupkur** [comment]
Already trying. Not working :( Please keep a look at https://github.com/elastic/elasticsearch/issues/40803

**Comment by aetter** [comment]
Gotcha, that's almost certainly an Elasticsearch bug---unfortunate to get hit by both at the same time. If you can, try disabling the security plugin temporarily, setting up the cluster how you'd like, and then re-enabling it. There's a simple toggle in `elasticsearch.yml`, although you won't be able to use Kibana until you've re-enabled it. https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/disable/
