### ISSUE TITLE
open distro  security plugin not working on 32-bit windows 8 machine

### ISSUE THREAD

**Issue by dVp007** [opendistro-for-elasticsearch/security#737]
When I started elastic search with security plugin installed in my 32-bit windows machine, elasticsearch didnt worked but when i removed the plugin and again started elasticsearch it was working well. Help needed

**Comment by vrozov** [comment]
Please provide logs, exceptions and error messages.

**Comment by dVp007** [comment]
I solved the problem by adding 
transport.host: localhost
transport.tcp.port: 9300 to the yml
Thankyou

**Comment by dVp007** [comment]
@
