### ISSUE TITLE
fix build package system to remove "advanced"

### ISSUE THREAD

**Issue by hardik-k-shah** [opendistro-for-elasticsearch/security#739]
mvn clean package -Padvanced 

"advanced" argument is no longer needed post merging of repositories.

**Comment by sujithvm** [comment]
- Merge advanced profile executions with maven assembly goals https://github.com/opendistro-for-elasticsearch/security/blob/master/pom.xml#L832 
- Remove checksum-maven-plugin 
- Remove -Padvanced from README.md, ci.yml, cd.yml (workflows) and any other reference to it
