### ISSUE TITLE
Can't reach Detections tab in SIEM due to permissions.

### ISSUE THREAD

**Issue by dizaar** [opendistro-for-elasticsearch/security#758]
Hi, I got issues opening Detections tab in SIEM.
ELK - 7.8.0
odfe - 1.9.0
Security is configured, tried to acces with both of internal user and ldap user with max permissions
I got such errors in elasticsearch log:
`[2020-10-03T23:56:23,862][ERROR][c.a.o.s.f.OpenDistroSecurityFilter] [od_elk_node1] Unexpected exception [_security] InvalidIndexNameException[Invalid index name [_sec
urity], must not start with '_'.]
org.elasticsearch.indices.InvalidIndexNameException: Invalid index name [_security], must not start with '_'.
`
`[2020-10-03T23:56:23,863][WARN ][r.suppressed             ] [od_elk_node1] path: /_security/user/_has_privileges, params: {index=_security, id=_has_privileges, type=user}
org.elasticsearch.ElasticsearchSecurityException: Unexpected exception indices:data/write/index
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:290) [opendistro_security-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:133) [opendistro_security-1.9.0.0.jar:1.9.0.0]
`
I get such errors in Kibana UI:
![изображение](https://user-images.githubusercontent.com/17981664/95001647-7d666400-05d4-11eb-8379-43212a8f7ee0.png)
![изображение](https://user-images.githubusercontent.com/17981664/95001564-d386d780-05d3-11eb-880a-ef42aa8ed547.png)
Don't know where to look for mistake in configuration.

**Comment by dizaar** [comment]
As I see using devtools in Chrome Kibana tries to request such url: https://<kibana_host>:5601/api/detection_engine/privileges.

**Comment by vrozov** [comment]
Likely you have Kibana plugin that requires X-Pack, please either use ODFE compatible plugins or raise a new issue with the corresponding Kibana plugin.
