### ISSUE TITLE
Unrecognized field "backend _roles"

### ISSUE THREAD

**Issue by maltefiala** [opendistro-for-elasticsearch/security#76]
We get an error when trying to add users using the API:

`{"type":"error","@timestamp":"2019-07-05T15:20:43Z","tags":[],"pid":1,"level":"error","error":{"message":"[unrecognized_property_exception] Unrecognized field \"backend _roles\" (class com.amazon.opendistroforelasticsearch.security.securityconf.impl.v6.InternalUserV6), not marked as ignorable (6 known properties: \"readonly\", \"userna me\", \"attributes\", \"hidden\", \"roles\", \"hash\"])\n at [Source: N/A; line: -1, column: -1] (through reference chain: com.amazon.opendistroforelasticsearch.securit y.securityconf.impl.v6.InternalUserV6[\"backend_roles\"]): [unrecognized_property_exception] Unrecognized field \"backend_roles\" (class com.amazon.opendistroforelastic search.security.securityconf.impl.v6.InternalUserV6)}}`

Might be connected to https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/44 and https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/43

**Comment by aetter** [comment]
Hi @maltefiala, the security API changed with 1.0.0/7.0.1. It looks like you might still be running V6, which correlates to the 0.x.x/6.x.x series.

It's still a backend role, but can you try `role` in the JSON body of your request?
