### ISSUE TITLE
Logstash doesn't launch up after upgrade ODFE from 0.9.0 to 1.0.0

### ISSUE THREAD

**Issue by AkiJ5** [opendistro-for-elasticsearch/security#77]
Hello! I have an issue after update my OpenDistro from 0.9.0 to 1.0.0: Logstash can't launch up properly.

What I did:

1. Stopped ELK service.
2. Made configuration backup with `securityadmin.sh `script.
3. Updated elasticsearch oss to 7.0.1 version.
4. Updated `opendistro-for-elasticsearch` package from repository.
5. Made migration of backup configuration with `securityadmin.sh` script.
6. Updated `opendistro-for-elastiksearch-kibana` from repository.
7. Updated logstash oss to 7.0.1 version.
8. Updated beats oss to 7.0.1.

Since that time logstash haven't started properly.

There is piece of logstash log:

[logstash.log](https://github.com/opendistro/for-elasticsearch/files/3367378/logstash.log)

And this one is piece of elasticsearch log:

[elasticsearch.log](https://github.com/opendistro/for-elasticsearch/files/3367379/elasticsearch.log)

In elasticsearch.yml I uncommented `node.name`, `network.host`, `http.port`, `cluster.initial_master_nodes` and changed only `network.host` field. My Elasticsearch config is bellow.

[elasticsearch_conf.txt](https://github.com/opendistro/for-elasticsearch/files/3367381/elasticsearch_conf.txt)

Explain me please, what I've done wrong and how to fix it.
Thx in advance.

**Comment by sgavrylenko** [comment]
have the same issue after logstash upgrade to v7.2.0

Logstash on starting send request to https://elastic:9200/_xpack and get 500 error
On elastic side in log appears the message:
```[2019-07-18T12:31:43,965][WARN ][r.suppressed             ] [elastic] path: /_xpack, params: {index=_xpack}
org.elasticsearch.ElasticsearchSecurityException: Unexpected exception indices:admin/get
...
[2019-07-18T12:31:43,966][ERROR][c.a.o.s.f.OpenDistroSecurityFilter] [elastic] Unexpected exception [_xpack] InvalidIndexNameException[Invalid index name [_xpack], must not start with '_'.]
```

**Comment by e11it** [comment]
Here is same issue https://discuss.opendistrocommunity.dev/t/logstash-oss-with-non-removable-x-pack/655/2

Solution is to set `ilm_enabled` to `false` in logstash config for es output.

```
output {
  elasticsearch { 
    hosts =>  [.. ]
    ilm_enabled => false
  }
}
```

**Comment by AkiJ5** [comment]
> Here is same issue https://discuss.opendistrocommunity.dev/t/logstash-oss-with-non-removable-x-pack/655/2

Thanks alot for your feedback!
I thought, I would not solve this issue :)
