### ISSUE TITLE
How to pseudonymize user data in open distro?

### ISSUE THREAD

**Issue by geheim01** [opendistro-for-elasticsearch/security#775]
What is the best practice on pseudonymize user data in logs in open distro?

**Comment by cliu123** [comment]
@geheim01 Could you provide more details on your use cases?

**Comment by geheim01** [comment]
Having logs containing for instance username or userid, I want to make sure it's gdpr compatible and turn this into pseudonyms.

**Comment by cliu123** [comment]
How is this related to Security plugin?

**Comment by geheim01** [comment]
It seemed the closest, because on the open distro website under Security GDPR Compliance is mentioned. Since pseudonymization is a part of GDPR Compliance I thought it would fit in here. If you have a better suggestion from a place where I could get a tip on this, I would be very happy!

**Comment by cliu123** [comment]
@geheim01 Could you kindly elaborate the use case?

**Comment by cliu123** [comment]
@geheim01 Please re-open the issue if you still need help.
