### ISSUE TITLE
Audit logging not logging user, permission.. etc deletion?

### ISSUE THREAD

**Issue by Ibrahim6161** [opendistro-for-elasticsearch/security#791]
Can the opendistro audit logging log if a user is deleted or created?

**Comment by sujithvm** [comment]
Yes audit log can log when user is deleted/created. 

There are two types of audit logging provided.
1. API Request auditing - audit REST and Transport requests that hit the security plugin
2. Compliance auditing - audit index for any read/write/update action. Here, the action of doc being read, written or updated is audit logged and not the request itself. 

Internal security index can be audited using compliance auditing as all internal users are stored in the .opendistro_security index. 
To enable, provide configuration in [audit.yml](https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/audit.yml#L52) (recommended) or if using the deprecated elasticsearch.yml setting `opendistro_security.compliance.history.internal_config_enabled: true"` . 
You can control logging the document content using settings like `write_metadata_only: false` `write_log_diffs: true` in audit.yml or equivalent deprecated elasticsearch.yml settings. 
Audit log event `COMPLIANCE_INTERNAL_CONFIG_WRITE` should be generated for create/update/delete actions.

**Comment by Ibrahim6161** [comment]
Worked like a charm! Thanks for your response. Have a nice day!

**Comment by cliu123** [comment]
Questions got answered. Closing the issue.
