### ISSUE TITLE
is opendistro security works for data forwarders? 

### ISSUE THREAD

**Issue by fedor-chemashkin** [opendistro-for-elasticsearch/security#8]
Does Open Distro support authentication for data forwarders (Logstash, FluentBit) using TLS or something else?

**Comment by hardik-k-shah** [comment]
Yes, Open Distro support authentication for data forwaders. 

Like for Logstash 
logtsash user needs to be configured in the elasticsearch output section of logstash.conf
```
output {
    elasticsearch {
       user => logstash
       password => logstash
       ssl: true,
    }
}
```
setting `ssl` to true ensures that logstash uses HTTPS.  

Optionally, you can also configure logstash to verify the hostname of the certificate it receives from Elasticsearch. You need to set the `ssl_certificate_verification` property to true and configure `cacert` parameter with absolute path to root CA.

Open Distro demo configuration already contain a logstash user with all required permissions. This user is configured in the internal user database.

**Comment by fedor-chemashkin** [comment]
Could you please provide example of configuration for FluentBit?
