### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by mancharagopan** [opendistro-for-elasticsearch/security#83]
Does it send email notifications?

**Comment by shivdoshi** [comment]
@mancharagopan The security plugin does not support sending email notification. 

Although, you can use the  alerting plugin along with security plugin to send notifications using webhooks. You can take a look at following docs to see this helps:
1. https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/
2. https://aws.amazon.com/blogs/opensource/open-distro-for-elasticsearch-alert-security-events/

**Comment by chuanzgh** [comment]
Interestingly, the Alerting webpage (https://opendistro.github.io/for-elasticsearch/features/alerting.html) shows SMTP notification as the [screenshot/showcase image](https://opendistro.github.io/for-elasticsearch/assets/media/screenshots/screen2.png)...
😆

**Comment by hardik-k-shah** [comment]
Please reopen if you still have questions.
