### ISSUE TITLE
Configuration Backup

### ISSUE THREAD

**Issue by georgiopandarez** [opendistro-for-elasticsearch/security#833]
Hi,

I have custom roles, users etc made via the kibana security plugin. I have a requirement to backup this configuration.n

I have tried using snapshots however bootstrapping a new node overrides it. There is no way to dump the config to yaml for importing via securityadmin.sh

There is an API method to dump the config as JSON, however the documentation gives a big fat warning saying that this can ruin your security configuration.

Please advise.

**Comment by vrozov** [comment]
Please see [backup, restore and migrate](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/security-admin/#backup-restore-and-migrate) section in the security admin documentation.
