### ISSUE TITLE
Opendistro 1.11.0 ES not finding roles_key from Okta Open ID JWT

### ISSUE THREAD

**Issue by chandu484** [opendistro-for-elasticsearch/security#837]
Hello All! We are testing SSO in ES and kibana with Opendistro ES. Found some issues.

1. I have installed Opendistro ES helm chart in Kubernetes! ES and kibana installed successfully!
Created config.yml and roles_mapping.yml . But somehow ES is not able to find roles_key *"roles" from okta openID JWT payload.I see the following warnings in client.

**Example JWT from okta:**
{
 "updated_at": 1605036112,
  "email_verified": true,
  "auth_time": 1605033579
  "roles": ["write"]
}
.
```
2020-11-10T20:45:44.818900317Z [2020-11-10T20:45:44,818][WARN ][c.a.d.a.h.j.AbstractHTTPJwtAuthenticator] [efk-es-client-7f784cbd55-jdd7v] Failed to get roles from JWT claims with roles_key 'roles'. Check if this key is correct and available in the JWT payload.
2020-11-10T20:46:38.061604650Z [2020-11-10T20:46:38,061][WARN ][c.a.o.s.h.HTTPBasicAuthenticator] [efk-es-client-7f784cbd55-jdd7v] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
2020-11-10T20:46:38.062137164Z [2020-11-10T20:46:38,061][INFO ][c.a.d.a.h.j.k.JwtVerifier] [efk-es-client-7f784cbd55-jdd7v] Escaped Key ID from JWT Token
```
**ES Security config.yml:**
    _meta:
      type: "config"
      config_version: 2
    config:
      dynamic:
        kibana:
          multitenancy_enabled: false
          server_username: admin
          index: '.kibana'
        do_not_fail_on_forbidden: false
        authc:
            basic_internal_auth_domain:
              http_enabled: true
              transport_enabled: true
              order: 0
              http_authenticator:
                type: basic
                challenge: false
              authentication_backend:
                type: internal
            openid_auth_domain:
              http_enabled: true
              transport_enabled: true
              order: 1
              http_authenticator:
                type: openid
                challenge: true
                config:
                  subject_key: preferred_username
                  roles_key: roles
                  openid_connect_url: https://company.okta.com/.well-known/openid-configuration
              authentication_backend:
                type: noop
**Sample roles_mapping.yml**:

_meta:
type: "rolesmapping"
config_version: 2

all_access:
reserved: false
backend_roles:
"admin"
"write" (this is the role attribute I created in okta. It was in the JWT payload as "roles": ["write"])
description: "Gives admin access"

- Users logging to kibana successfully but the **roles** attribute is not showing any impact even though I mapped roles to users in okta and mentioned that attribute name in ES config. Any help would be much appreciated.Thank you in advance!

**Comment by palashhedau** [comment]
Roles Key -  The value of this key must be a comma-separated list of roles.

This shouldn't be an array. This should be comma separated string in JWT payload - "role1,role2".

Please reopen in case issue is not resolved.

**Comment by chandu484** [comment]
Hello @palashhedau I tried single role string in roles key from JWT! But still no luck! getting same error! "Failed to get roles from JWT claims with roles_key 'roles'. Check if this key is correct and available in the JWT payload"! In Kibana UI I see backend roles as empty!
![image](https://user-images.githubusercontent.com/53717126/103563112-d1a60c00-4e81-11eb-8b78-83b768d9136c.png)

{
  "roles": "**write**"
}
