### ISSUE TITLE
Error in the creation of reserved users

### ISSUE THREAD

**Issue by SitoRBJ** [opendistro-for-elasticsearch/security#842]
Hello, everybody.

I have the following problem. In an environment already created, where I have reserved users created using the file internal_users.yml I also have created users from the ODFE-Kibana UI. 

I have to add a new reserved user. The fact is that I add it to my file internal_users.yml and I execute the script to load that file:

```bash
bash /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -f /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml -icl -key /etc/elasticsearch/kirk-key.pem -cert /etc/elasticsearch/kirk.pem -cacert /etc/elasticsearch/root-ca.pem -h  odfe -nhnv
```

The problem is that by running this script. All users created from the UI are deleted. 

Is there a solution for this?

Thank you in advance.

Regards

**Comment by vrozov** [comment]
The behavior is expected. Please see documentation how to backup existing users and/or roles. To add reserved users, please backup users and add reserved users to the backup copy.

**Comment by SitoRBJ** [comment]
Yes, just that I was seeing, the basic idea is to download using the backup flag, modify and upload. Thank you very much.
