### ISSUE TITLE
Opendistro 1.0.2 Security Vulnerabilities

### ISSUE THREAD

**Issue by gferrette** [opendistro-for-elasticsearch/security#883]
Hello,

Please, it's just a question. I'm using Opendistro 1.0.2 in production, is there any security vulnerability in this version that justifies the version upgrade?

Thanks in Advance!

**Comment by cliu123** [comment]
Release notes for each release summarize the enhancements, bug fixes and maintenance improvements in that release.
https://github.com/opendistro-for-elasticsearch/security/blob/master/release-notes/opendistro-for-elasticsearch-security.release-notes-1.12.0.0.md
Please feel free to re-open the issue in case the release notes don't answer your question.

**Comment by vrozov** [comment]
@cliu123 1.12.0.0 is not released yet.

@gferrette Upgrades from older ODFE versions are mostly driven by supported ES version, so I would recommend upgrading to the recent ODFE version even though, AFAIK, there are no critical security vulnerabilities in the security plugin.

**Comment by gferrette** [comment]
Hello @vrozov, @cliu123 

@vrozov , Thanks for replying, do you mean that as far as you know there are no critical vulnerabilities in the security plugin on 1.0.2 version?

We are waiting to version 1.12.0.0 to be released to upgrade, because there was a bug on 1.11 version on read only profiles that was already fixed, but this fix will be available on 1.12 version.

Thanks again.

**Comment by vrozov** [comment]
Right, I am not aware of any critical vulnerabilities in the 1.0.2.0 security plugin.
