### ISSUE TITLE
Set up a single sign-on for multiple Azure Active Directory domains?

### ISSUE THREAD

**Issue by jaisegrg** [opendistro-for-elasticsearch/security#904]
Hi,

I have setup SSO for Opendistro Kibana using Azure AD- Keycloak-OpenID Connect using single domain and its working perfectly.

Could you please help on setting up SSO using multiple domains?

1. Using OpenID connect.
2. Using SAML.

**Comment by cliu123** [comment]
Please check this doc to set up multiple authentication domains: https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/saml/#running-multiple-authentication-domains
Here is the doc on how to set up openId domain: https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/openid-connect/#configure-openid-connect-integration
Please feel free to reopen the issue if these info doesn't help you.

**Comment by jaisegrg** [comment]
Hi @cliu123,

Can you please suggest how can i configure multiple domains using OpenID connect? Its working fine with single domain and here is the Kibana configuration. How can i add the same for multiple domains? Please suggest.

opendistro_security.auth.type: "openid"
opendistro_security.openid.connect_url: "https://<keycloak_url>/auth/realms/test/.well-known/openid-configuration"
opendistro_security.openid.client_id: "<keycloak_client_id>"
opendistro_security.openid.client_secret: "<keycloak_client_secret>"
opendistro_security.openid.base_redirect_url: "https://<kibana_ip>:5601/"

**Comment by jaisegrg** [comment]
@cliu123,

Or Can you please suggest multiple authentication configurations using SAML? 

We are using Opendistro ELK + Keycloak + Azure AD (multiple authentication).
