### ISSUE TITLE
Trying to create App level permission

### ISSUE THREAD

**Issue by vehere-ccu3** [opendistro-for-elasticsearch/security#909]
Hi,

I am trying to achieve Application level permission, based on roles. What my idea is to use a field like 'appPermissions' simialr to 'indexPermissions' or 'clusterPermissions', from kibana.yml,  which will contain an array of permissible app ids, such as ['app:discover', 'app:dashboards',....], which further could be clubbed in action groups or could be used singly and associated with roles. Similar action like with clusterPermissions.

In the react code I created the configuration parameters, and the constant list, but I want to achieve this through the index, I want to save the permissions app_permissions field in the index, for a particular role, while trying to insert this field through API i got an error saying:

```
{
  "status" : "error",
  "reason" : "Invalid configuration",
  "invalid_keys" : {
    "keys" : "app_permissions"
  }
}
```

Following is the API query:

```
PUT _opendistro/_security/api/roles/approle
{
  "app_permissions": [
    "app:home",
    "app:discover",
    "app:dashboards",
    "app:visualize"
  ],
  "cluster_permissions": [
    "cluster_composite_ops",
    "indices_monitor"
  ],
  "index_permissions": [{
    "index_patterns": [
      "movies*"
    ],
    "dls": "",
    "fls": [],
    "masked_fields": [],
    "allowed_actions": [
      "read"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "human_resources"
    ],
    "allowed_actions": [
      "kibana_all_read"
    ]
  }]
}
```

Can anyone help me on where to start in the ES plugin end to achieve this?

**Comment by vrozov** [comment]
"app_permissions" is not supported as part of the roles.

**Comment by vehere-ccu3** [comment]
Yeah I know that "app_permissions" is not supported. That was my question actually if I want to add the field then where should I start.

**Comment by vrozov** [comment]
There is no plan to add "app_permissions" or custom roles. You may start with creating proposal and justification (use cases) why such functionality will be useful for others.
