### ISSUE TITLE
[FEATURE REQUEST] Modifying security config.yaml post initial config. 

### ISSUE THREAD

**Issue by gamebrigada** [opendistro-for-elasticsearch/security#947]
Configured AD authentication almost a year ago and didn't audit that the settings took correctly. Now need to enforce SSL for AD, and in Kibana SSL. Many changes have been made to the initial configuration since it was made many months ago in a production environment. Reapplying the config will delete dozens of production accounts. 

There must be a better way. Things need to be able to change at a low level like this.

**Comment by vrozov** [comment]
Please see doc how changes can be applied to the security config
