### ISSUE TITLE
User-Role mapping in security should be case-insensitive for usernames

### ISSUE THREAD

**Issue by sushovan23** [opendistro-for-elasticsearch/security#971]
Current behavior - User - Role mapping is case sensitive. If I map user test1 with role all_access
Then is user Test1 login which is same user as test1 but since the user - role mapping is for user test1 instead of Test1 it doesn't get the access. 
Expected behavior - User - Role mapping becomes case insensitive.

**Comment by debjanibnrj** [comment]
This is as per design, We will treat username with different case as unique.
