### ISSUE TITLE
Index Management be system-wide (rather than tenant-specific)

### ISSUE THREAD

**Issue by verbecee** [opendistro-for-elasticsearch/security#988]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I need to create an index pattern that should apply to all tenants, but can only create it in tenants individually.

**Describe the solution you'd like**
It would be nice to manage index patterns globally rather than in a tenant-specific manner. For example, we have 10 tenants (a team per tenant), and we would like all 100+ index patterns we've created in one tenant to apply to all tenants. Rather than having to take the time to create the patterns across tenants or come up with some back-end hack, would be nice if this was a feature to begin with. 

**Describe alternatives you've considered**
We haven't had time to try anything else, but have asked our separate teams to use a common tenant to see all index patterns.

**Additional context**

**Comment by hardik-k-shah** [comment]
Multi-tenancy is applicable for all kibana objects including index patterns, visualization and dashboards. 

Global tenant/shared tenant is for such usecases when you want to share everything across all users/roles. 

Additionally, if you do not wish to use multi-tenancy features and allow all kibana objects for everyone, you can disable multi-tenancy.  Details are documented here: https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#configuration

**Comment by verbecee** [comment]
@hardik-k-shah we don't want to eliminate multi-tenancy for our cluster - we have tenants who have specific permissions to see only certain indices/documents. The problem is that MOST of our tenants would be benefit from the 100+ index patterns we have written, but we want them to be able to store their own objects in their own tenants. But recreating and maintaining the same 100+ index patterns across individual tenants (which we have over 10) is not feasible. @dbbaughe thanks for the transfer, I'll take it up over there.
