### ISSUE TITLE
[Feature Request] AWS IAM as authentication backend

### ISSUE THREAD

**Issue by root360-AndreasUlm** [opendistro-for-elasticsearch/security#995]
Hi,

I haven't found any hint in the authentication configuration [1] whcih is why I'm creating an issue.
It would be a nice feature to be able to use AWS IAM as authentication backend.
There seems to be a possibility as there is already a plugin for kubernetes [2] but I could not yet find a way to port it to opendistro-for-elasticsearch.

Regards,
Andreas

[1] https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/concepts/
[2] https://github.com/kubernetes-sigs/aws-iam-authenticator

**Comment by cliu123** [comment]
AWS Elasticsearch supports policy-based identity and access control, which is based on AWS IAM. Please see the [documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html).

**Comment by root360-AndreasUlm** [comment]
@cliu123  This issue is not about AWS Elasticsearch but AWS IAM support in opendistro-for-elasticsearch.
We are running our own Elasticsearch cluster with opendistro-for-elasticsearch as part of our [Wazuh](https://wazuh.com/) setup.
Due to the limited nature of AWS Elasticsearch concerning installation of plugins we cannot use AWS Elasticsearch.
