### ISSUE TITLE
Updating internal user without new password resulting error

### ISSUE THREAD

**Issue by yuxitang-amzn** [opendistro-for-elasticsearch/security#996]
ES & Kibana version: 7.10
Opendistro version: 1.12

I'm updating an existing user with admin, and it shows error on save.
![image](https://user-images.githubusercontent.com/63078162/106070749-ead55d80-60b9-11eb-8fc0-4db07287f07f.png)

Tested in OD 1.11 and it saved without any error.

It seems relates to https://github.com/opendistro-for-elasticsearch/security/pull/818. Understood that we should not create user with empty password. But a empty password in a user update request means we only want to update backend role / attribute but not password.

**Comment by vrozov** [comment]
In case you want to update only backend roles/attributes don't send password at all in the request. Empty password should not be included in such requests.

**Comment by yuxitang-amzn** [comment]
Did some tests.

Let's say:
Error A: "Please specify either 'hash' or 'password' when creating a new internal user."
Error B: "Password does not match minimum criteria"

In 1.11:

||password not present|password = ""|
|--|--|--|
|create|Error A|Error A|
|update|No error| No error|

In 1.12:

||password not present|password = ""|
|--|--|--|
|create|Error A|Error B|
|update|No error|Error B|

To me the ideal case would be no error (no behavior change) for update (either password is not present or is empty).

**Comment by vrozov** [comment]
@yuxitang-amzn If password is specified (whether it is empty or not), security plugin should not ignore it as it cannot reliably determine whether or not user wants to update password to be an empty password or wants to update roles only. It is very easy to avoid ambiguity by not specifying password in the update request if user does not want to update it.

@cliu123 Have you communicated API change to the kibana team?

**Comment by cliu123** [comment]
> @yuxitang-amzn If password is specified (whether it is empty or not), security plugin should not ignore it as it cannot reliably determine whether or not user wants to update password to be an empty password or wants to update roles only. It is very easy to avoid ambiguity by not specifying password in the update request if user does not want to update it.
> 
> @cliu123 Have you communicated API change to the kibana team?

@vrozov  I emailed zengyan-amazon@ and asked for the risk of this changes before making the changes.

**Comment by cliu123** [comment]
> Did some tests.
> 
> Let's say:
> Error A: "Please specify either 'hash' or 'password' when creating a new internal user."
> Error B: "Password does not match minimum criteria"
> 
> In 1.11:
> 
> password not present	password = ""
> create	Error A	Error A
> update	No error	No error
> In 1.12:
> 
> password not present	password = ""
> create	Error A	Error B
> update	No error	Error B
> To me the ideal case would be no error (no behavior change) for update (either password is not present or is empty).

@yuxitang-amzn Based on your testing, the case of update*password works with no error, so it doesn't block users from updating only backend role / attribute. Security plugin made this change because an exception happened in deserialization due to empty password. I believe vrozov@ already explained the reason why security plugin blocks empty password above.

**Comment by yuxitang-amzn** [comment]
Understood, will proceed to update kibana security plugin accordingly in 1.13.

**Comment by cliu123** [comment]
Sounds good. Thanks! @yuxitang-amzn
