### ISSUE TITLE
Roles mapping "add" delete pre defined backend_roles

### ISSUE THREAD

**Issue by FaelDi** [opendistro-for-elasticsearch/security#998]
Hi guys, 
I have a role called "workaround_role", when a Company Access my kibana module for the first time a backend service check if its created, if its not it create like this:

curl -X PATCH -H 'Content-Type: application/json' 'OUR URL to create' -d '
[
  {
    "op": "add", "path": "/workaround_role", "value": { "backend_roles": ["COMPANY1-MODELER", "COMPANY1-ADMINISTRATOR", "COMPANY1-ANALYST"] }
  }
]'

and it's create perfectly
wordaround_role -> mapping users : COMPANY1-MODELER", "COMPANY1-ADMINISTRATOR", "COMPANY1-ANALYST

The problem:
The problem occours when a second company acess the module, so the opendistro security should use the same script to add in the workaround_role the name of the company2 but keeping the company1

should be like this: ( we're using PATCH ) 
wordaround_role -> mapping users : COMPANY1-MODELER", "COMPANY1-ADMINISTRATOR", "COMPANY1-ANALYST, COMPANY2-MODELER", "COMPANY2-ADMINISTRATOR", "COMPANY2-ANALYST,

But the script do a "op": "replace" and not include the new backend roles, it exclude the pre defined ones and include only the new ones

stay like this:
wordaround_role -> mapping users :  COMPANY2-MODELER", "COMPANY2-ADMINISTRATOR", "COMPANY2-ANALYST

Why the older backend_roles is not kepping? we are using "add" with PATCH, it should only include the new backend roles, it's like the role is deleted and created with the new ones.

**Comment by cliu123** [comment]
Looks like you are creating users. Please see [the documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#patch-users). Request with `"op":"add"` creates new users. [Here](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#request-19) is the documentation for creating/updating/deleting roles. 
If you want to keep the existing backend roles of the user, you can do `"op":"add"`/`"op":"replace"`with `existing backend roles + new backend roles`.
